// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: shard_lookup.proto

#include "shard_lookup.pb.h"
#include "shard_lookup.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace gluten {
namespace shard {
namespace proto {

static const char* ShardLookupService_method_names[] = {
  "/gluten.shard.proto.ShardLookupService/Lookup",
  "/gluten.shard.proto.ShardLookupService/BatchLookup",
};

std::unique_ptr< ShardLookupService::Stub> ShardLookupService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ShardLookupService::Stub> stub(new ShardLookupService::Stub(channel, options));
  return stub;
}

ShardLookupService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Lookup_(ShardLookupService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchLookup_(ShardLookupService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ShardLookupService::Stub::Lookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::gluten::shard::proto::LookupResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gluten::shard::proto::LookupRequest, ::gluten::shard::proto::LookupResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Lookup_, context, request, response);
}

void ShardLookupService::Stub::async::Lookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest* request, ::gluten::shard::proto::LookupResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gluten::shard::proto::LookupRequest, ::gluten::shard::proto::LookupResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Lookup_, context, request, response, std::move(f));
}

void ShardLookupService::Stub::async::Lookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest* request, ::gluten::shard::proto::LookupResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Lookup_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::LookupResponse>* ShardLookupService::Stub::PrepareAsyncLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gluten::shard::proto::LookupResponse, ::gluten::shard::proto::LookupRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Lookup_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::LookupResponse>* ShardLookupService::Stub::AsyncLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLookupRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ShardLookupService::Stub::BatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::gluten::shard::proto::BatchLookupResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::gluten::shard::proto::BatchLookupRequest, ::gluten::shard::proto::BatchLookupResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchLookup_, context, request, response);
}

void ShardLookupService::Stub::async::BatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest* request, ::gluten::shard::proto::BatchLookupResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::gluten::shard::proto::BatchLookupRequest, ::gluten::shard::proto::BatchLookupResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchLookup_, context, request, response, std::move(f));
}

void ShardLookupService::Stub::async::BatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest* request, ::gluten::shard::proto::BatchLookupResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchLookup_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::BatchLookupResponse>* ShardLookupService::Stub::PrepareAsyncBatchLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::gluten::shard::proto::BatchLookupResponse, ::gluten::shard::proto::BatchLookupRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchLookup_, context, request);
}

::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::BatchLookupResponse>* ShardLookupService::Stub::AsyncBatchLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchLookupRaw(context, request, cq);
  result->StartCall();
  return result;
}

ShardLookupService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShardLookupService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShardLookupService::Service, ::gluten::shard::proto::LookupRequest, ::gluten::shard::proto::LookupResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ShardLookupService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gluten::shard::proto::LookupRequest* req,
             ::gluten::shard::proto::LookupResponse* resp) {
               return service->Lookup(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ShardLookupService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ShardLookupService::Service, ::gluten::shard::proto::BatchLookupRequest, ::gluten::shard::proto::BatchLookupResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ShardLookupService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::gluten::shard::proto::BatchLookupRequest* req,
             ::gluten::shard::proto::BatchLookupResponse* resp) {
               return service->BatchLookup(ctx, req, resp);
             }, this)));
}

ShardLookupService::Service::~Service() {
}

::grpc::Status ShardLookupService::Service::Lookup(::grpc::ServerContext* context, const ::gluten::shard::proto::LookupRequest* request, ::gluten::shard::proto::LookupResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ShardLookupService::Service::BatchLookup(::grpc::ServerContext* context, const ::gluten::shard::proto::BatchLookupRequest* request, ::gluten::shard::proto::BatchLookupResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace gluten
}  // namespace shard
}  // namespace proto

