// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: shard_lookup.proto
// Original file comments:
// Protocol buffer definition for ShardServer gRPC lookup service.
// Used by ShardLookupJoin (probe side) to issue batched async remote lookups.
//
#ifndef GRPC_shard_5flookup_2eproto__INCLUDED
#define GRPC_shard_5flookup_2eproto__INCLUDED

#include "shard_lookup.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace gluten {
namespace shard {
namespace proto {

// ---------------------------------------------------------------------------
// ShardLookupService – served by each executor's ShardServer.
// ---------------------------------------------------------------------------
class ShardLookupService final {
 public:
  static constexpr char const* service_full_name() {
    return "gluten.shard.proto.ShardLookupService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Perform a batched index lookup against a local shard hash table.
    virtual ::grpc::Status Lookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::gluten::shard::proto::LookupResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::LookupResponse>> AsyncLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::LookupResponse>>(AsyncLookupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::LookupResponse>> PrepareAsyncLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::LookupResponse>>(PrepareAsyncLookupRaw(context, request, cq));
    }
    // Perform lookups against multiple shards in a single RPC call.
    // This reduces RPC count when an executor hosts many shards: instead of
    // one RPC per shard, the client groups all shards on the same remote
    // address into one BatchLookup call.  For 200 shards across 10 machines,
    // this cuts RPC count from 200 to 10 per probe batch.
    virtual ::grpc::Status BatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::gluten::shard::proto::BatchLookupResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::BatchLookupResponse>> AsyncBatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::BatchLookupResponse>>(AsyncBatchLookupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::BatchLookupResponse>> PrepareAsyncBatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::BatchLookupResponse>>(PrepareAsyncBatchLookupRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Perform a batched index lookup against a local shard hash table.
      virtual void Lookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest* request, ::gluten::shard::proto::LookupResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Lookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest* request, ::gluten::shard::proto::LookupResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Perform lookups against multiple shards in a single RPC call.
      // This reduces RPC count when an executor hosts many shards: instead of
      // one RPC per shard, the client groups all shards on the same remote
      // address into one BatchLookup call.  For 200 shards across 10 machines,
      // this cuts RPC count from 200 to 10 per probe batch.
      virtual void BatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest* request, ::gluten::shard::proto::BatchLookupResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void BatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest* request, ::gluten::shard::proto::BatchLookupResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::LookupResponse>* AsyncLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::LookupResponse>* PrepareAsyncLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::BatchLookupResponse>* AsyncBatchLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gluten::shard::proto::BatchLookupResponse>* PrepareAsyncBatchLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Lookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::gluten::shard::proto::LookupResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::LookupResponse>> AsyncLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::LookupResponse>>(AsyncLookupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::LookupResponse>> PrepareAsyncLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::LookupResponse>>(PrepareAsyncLookupRaw(context, request, cq));
    }
    ::grpc::Status BatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::gluten::shard::proto::BatchLookupResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::BatchLookupResponse>> AsyncBatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::BatchLookupResponse>>(AsyncBatchLookupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::BatchLookupResponse>> PrepareAsyncBatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::BatchLookupResponse>>(PrepareAsyncBatchLookupRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Lookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest* request, ::gluten::shard::proto::LookupResponse* response, std::function<void(::grpc::Status)>) override;
      void Lookup(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest* request, ::gluten::shard::proto::LookupResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void BatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest* request, ::gluten::shard::proto::BatchLookupResponse* response, std::function<void(::grpc::Status)>) override;
      void BatchLookup(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest* request, ::gluten::shard::proto::BatchLookupResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::LookupResponse>* AsyncLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::LookupResponse>* PrepareAsyncLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::LookupRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::BatchLookupResponse>* AsyncBatchLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gluten::shard::proto::BatchLookupResponse>* PrepareAsyncBatchLookupRaw(::grpc::ClientContext* context, const ::gluten::shard::proto::BatchLookupRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Lookup_;
    const ::grpc::internal::RpcMethod rpcmethod_BatchLookup_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Perform a batched index lookup against a local shard hash table.
    virtual ::grpc::Status Lookup(::grpc::ServerContext* context, const ::gluten::shard::proto::LookupRequest* request, ::gluten::shard::proto::LookupResponse* response);
    // Perform lookups against multiple shards in a single RPC call.
    // This reduces RPC count when an executor hosts many shards: instead of
    // one RPC per shard, the client groups all shards on the same remote
    // address into one BatchLookup call.  For 200 shards across 10 machines,
    // this cuts RPC count from 200 to 10 per probe batch.
    virtual ::grpc::Status BatchLookup(::grpc::ServerContext* context, const ::gluten::shard::proto::BatchLookupRequest* request, ::gluten::shard::proto::BatchLookupResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Lookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Lookup() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Lookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Lookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::LookupRequest* /*request*/, ::gluten::shard::proto::LookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLookup(::grpc::ServerContext* context, ::gluten::shard::proto::LookupRequest* request, ::grpc::ServerAsyncResponseWriter< ::gluten::shard::proto::LookupResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BatchLookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_BatchLookup() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_BatchLookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchLookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::BatchLookupRequest* /*request*/, ::gluten::shard::proto::BatchLookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchLookup(::grpc::ServerContext* context, ::gluten::shard::proto::BatchLookupRequest* request, ::grpc::ServerAsyncResponseWriter< ::gluten::shard::proto::BatchLookupResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Lookup<WithAsyncMethod_BatchLookup<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Lookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Lookup() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::gluten::shard::proto::LookupRequest, ::gluten::shard::proto::LookupResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::gluten::shard::proto::LookupRequest* request, ::gluten::shard::proto::LookupResponse* response) { return this->Lookup(context, request, response); }));}
    void SetMessageAllocatorFor_Lookup(
        ::grpc::MessageAllocator< ::gluten::shard::proto::LookupRequest, ::gluten::shard::proto::LookupResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::gluten::shard::proto::LookupRequest, ::gluten::shard::proto::LookupResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Lookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Lookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::LookupRequest* /*request*/, ::gluten::shard::proto::LookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Lookup(
      ::grpc::CallbackServerContext* /*context*/, const ::gluten::shard::proto::LookupRequest* /*request*/, ::gluten::shard::proto::LookupResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_BatchLookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_BatchLookup() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::gluten::shard::proto::BatchLookupRequest, ::gluten::shard::proto::BatchLookupResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::gluten::shard::proto::BatchLookupRequest* request, ::gluten::shard::proto::BatchLookupResponse* response) { return this->BatchLookup(context, request, response); }));}
    void SetMessageAllocatorFor_BatchLookup(
        ::grpc::MessageAllocator< ::gluten::shard::proto::BatchLookupRequest, ::gluten::shard::proto::BatchLookupResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::gluten::shard::proto::BatchLookupRequest, ::gluten::shard::proto::BatchLookupResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_BatchLookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchLookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::BatchLookupRequest* /*request*/, ::gluten::shard::proto::BatchLookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BatchLookup(
      ::grpc::CallbackServerContext* /*context*/, const ::gluten::shard::proto::BatchLookupRequest* /*request*/, ::gluten::shard::proto::BatchLookupResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Lookup<WithCallbackMethod_BatchLookup<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Lookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Lookup() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Lookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Lookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::LookupRequest* /*request*/, ::gluten::shard::proto::LookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BatchLookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_BatchLookup() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_BatchLookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchLookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::BatchLookupRequest* /*request*/, ::gluten::shard::proto::BatchLookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Lookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Lookup() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Lookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Lookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::LookupRequest* /*request*/, ::gluten::shard::proto::LookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLookup(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_BatchLookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_BatchLookup() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_BatchLookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchLookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::BatchLookupRequest* /*request*/, ::gluten::shard::proto::BatchLookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBatchLookup(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Lookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Lookup() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Lookup(context, request, response); }));
    }
    ~WithRawCallbackMethod_Lookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Lookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::LookupRequest* /*request*/, ::gluten::shard::proto::LookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Lookup(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_BatchLookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_BatchLookup() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->BatchLookup(context, request, response); }));
    }
    ~WithRawCallbackMethod_BatchLookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BatchLookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::BatchLookupRequest* /*request*/, ::gluten::shard::proto::BatchLookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BatchLookup(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Lookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Lookup() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::gluten::shard::proto::LookupRequest, ::gluten::shard::proto::LookupResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::gluten::shard::proto::LookupRequest, ::gluten::shard::proto::LookupResponse>* streamer) {
                       return this->StreamedLookup(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Lookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Lookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::LookupRequest* /*request*/, ::gluten::shard::proto::LookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLookup(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gluten::shard::proto::LookupRequest,::gluten::shard::proto::LookupResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BatchLookup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_BatchLookup() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::gluten::shard::proto::BatchLookupRequest, ::gluten::shard::proto::BatchLookupResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::gluten::shard::proto::BatchLookupRequest, ::gluten::shard::proto::BatchLookupResponse>* streamer) {
                       return this->StreamedBatchLookup(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_BatchLookup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BatchLookup(::grpc::ServerContext* /*context*/, const ::gluten::shard::proto::BatchLookupRequest* /*request*/, ::gluten::shard::proto::BatchLookupResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBatchLookup(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gluten::shard::proto::BatchLookupRequest,::gluten::shard::proto::BatchLookupResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Lookup<WithStreamedUnaryMethod_BatchLookup<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Lookup<WithStreamedUnaryMethod_BatchLookup<Service > > StreamedService;
};

}  // namespace proto
}  // namespace shard
}  // namespace gluten


#endif  // GRPC_shard_5flookup_2eproto__INCLUDED
