// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shard_lookup.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_shard_5flookup_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_shard_5flookup_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_shard_5flookup_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_shard_5flookup_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_shard_5flookup_2eproto;
namespace gluten {
namespace shard {
namespace proto {
class BatchLookupRequest;
struct BatchLookupRequestDefaultTypeInternal;
extern BatchLookupRequestDefaultTypeInternal _BatchLookupRequest_default_instance_;
class BatchLookupResponse;
struct BatchLookupResponseDefaultTypeInternal;
extern BatchLookupResponseDefaultTypeInternal _BatchLookupResponse_default_instance_;
class LookupRequest;
struct LookupRequestDefaultTypeInternal;
extern LookupRequestDefaultTypeInternal _LookupRequest_default_instance_;
class LookupResponse;
struct LookupResponseDefaultTypeInternal;
extern LookupResponseDefaultTypeInternal _LookupResponse_default_instance_;
class ShardLookupEntry;
struct ShardLookupEntryDefaultTypeInternal;
extern ShardLookupEntryDefaultTypeInternal _ShardLookupEntry_default_instance_;
class ShardLookupResultEntry;
struct ShardLookupResultEntryDefaultTypeInternal;
extern ShardLookupResultEntryDefaultTypeInternal _ShardLookupResultEntry_default_instance_;
}  // namespace proto
}  // namespace shard
}  // namespace gluten
PROTOBUF_NAMESPACE_OPEN
template<> ::gluten::shard::proto::BatchLookupRequest* Arena::CreateMaybeMessage<::gluten::shard::proto::BatchLookupRequest>(Arena*);
template<> ::gluten::shard::proto::BatchLookupResponse* Arena::CreateMaybeMessage<::gluten::shard::proto::BatchLookupResponse>(Arena*);
template<> ::gluten::shard::proto::LookupRequest* Arena::CreateMaybeMessage<::gluten::shard::proto::LookupRequest>(Arena*);
template<> ::gluten::shard::proto::LookupResponse* Arena::CreateMaybeMessage<::gluten::shard::proto::LookupResponse>(Arena*);
template<> ::gluten::shard::proto::ShardLookupEntry* Arena::CreateMaybeMessage<::gluten::shard::proto::ShardLookupEntry>(Arena*);
template<> ::gluten::shard::proto::ShardLookupResultEntry* Arena::CreateMaybeMessage<::gluten::shard::proto::ShardLookupResultEntry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gluten {
namespace shard {
namespace proto {

// ===================================================================

class LookupRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gluten.shard.proto.LookupRequest) */ {
 public:
  inline LookupRequest() : LookupRequest(nullptr) {}
  ~LookupRequest() override;
  explicit PROTOBUF_CONSTEXPR LookupRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LookupRequest(const LookupRequest& from);
  LookupRequest(LookupRequest&& from) noexcept
    : LookupRequest() {
    *this = ::std::move(from);
  }

  inline LookupRequest& operator=(const LookupRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LookupRequest& operator=(LookupRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LookupRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LookupRequest* internal_default_instance() {
    return reinterpret_cast<const LookupRequest*>(
               &_LookupRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LookupRequest& a, LookupRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(LookupRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LookupRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LookupRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LookupRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LookupRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LookupRequest& from) {
    LookupRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LookupRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gluten.shard.proto.LookupRequest";
  }
  protected:
  explicit LookupRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputIndicesFieldNumber = 4,
    kProbeKeysCompactFieldNumber = 3,
    kProbeFilterColumnsCompactFieldNumber = 5,
    kFilterExpressionFieldNumber = 6,
    kProbeColumnsTypeFieldNumber = 7,
    kFilterInputTypeFieldNumber = 8,
    kSetIdFieldNumber = 1,
    kShardIdFieldNumber = 2,
  };
  // repeated int32 input_indices = 4;
  int input_indices_size() const;
  private:
  int _internal_input_indices_size() const;
  public:
  void clear_input_indices();
  private:
  int32_t _internal_input_indices(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_input_indices() const;
  void _internal_add_input_indices(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_input_indices();
  public:
  int32_t input_indices(int index) const;
  void set_input_indices(int index, int32_t value);
  void add_input_indices(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      input_indices() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_input_indices();

  // bytes probe_keys_compact = 3;
  void clear_probe_keys_compact();
  const std::string& probe_keys_compact() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_probe_keys_compact(ArgT0&& arg0, ArgT... args);
  std::string* mutable_probe_keys_compact();
  PROTOBUF_NODISCARD std::string* release_probe_keys_compact();
  void set_allocated_probe_keys_compact(std::string* probe_keys_compact);
  private:
  const std::string& _internal_probe_keys_compact() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_probe_keys_compact(const std::string& value);
  std::string* _internal_mutable_probe_keys_compact();
  public:

  // bytes probe_filter_columns_compact = 5;
  void clear_probe_filter_columns_compact();
  const std::string& probe_filter_columns_compact() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_probe_filter_columns_compact(ArgT0&& arg0, ArgT... args);
  std::string* mutable_probe_filter_columns_compact();
  PROTOBUF_NODISCARD std::string* release_probe_filter_columns_compact();
  void set_allocated_probe_filter_columns_compact(std::string* probe_filter_columns_compact);
  private:
  const std::string& _internal_probe_filter_columns_compact() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_probe_filter_columns_compact(const std::string& value);
  std::string* _internal_mutable_probe_filter_columns_compact();
  public:

  // string filter_expression = 6;
  void clear_filter_expression();
  const std::string& filter_expression() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filter_expression(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filter_expression();
  PROTOBUF_NODISCARD std::string* release_filter_expression();
  void set_allocated_filter_expression(std::string* filter_expression);
  private:
  const std::string& _internal_filter_expression() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filter_expression(const std::string& value);
  std::string* _internal_mutable_filter_expression();
  public:

  // string probe_columns_type = 7;
  void clear_probe_columns_type();
  const std::string& probe_columns_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_probe_columns_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_probe_columns_type();
  PROTOBUF_NODISCARD std::string* release_probe_columns_type();
  void set_allocated_probe_columns_type(std::string* probe_columns_type);
  private:
  const std::string& _internal_probe_columns_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_probe_columns_type(const std::string& value);
  std::string* _internal_mutable_probe_columns_type();
  public:

  // string filter_input_type = 8;
  void clear_filter_input_type();
  const std::string& filter_input_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filter_input_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filter_input_type();
  PROTOBUF_NODISCARD std::string* release_filter_input_type();
  void set_allocated_filter_input_type(std::string* filter_input_type);
  private:
  const std::string& _internal_filter_input_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filter_input_type(const std::string& value);
  std::string* _internal_mutable_filter_input_type();
  public:

  // int64 set_id = 1;
  void clear_set_id();
  int64_t set_id() const;
  void set_set_id(int64_t value);
  private:
  int64_t _internal_set_id() const;
  void _internal_set_set_id(int64_t value);
  public:

  // int32 shard_id = 2;
  void clear_shard_id();
  int32_t shard_id() const;
  void set_shard_id(int32_t value);
  private:
  int32_t _internal_shard_id() const;
  void _internal_set_shard_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:gluten.shard.proto.LookupRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > input_indices_;
    mutable std::atomic<int> _input_indices_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr probe_keys_compact_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr probe_filter_columns_compact_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filter_expression_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr probe_columns_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filter_input_type_;
    int64_t set_id_;
    int32_t shard_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shard_5flookup_2eproto;
};
// -------------------------------------------------------------------

class LookupResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gluten.shard.proto.LookupResponse) */ {
 public:
  inline LookupResponse() : LookupResponse(nullptr) {}
  ~LookupResponse() override;
  explicit PROTOBUF_CONSTEXPR LookupResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LookupResponse(const LookupResponse& from);
  LookupResponse(LookupResponse&& from) noexcept
    : LookupResponse() {
    *this = ::std::move(from);
  }

  inline LookupResponse& operator=(const LookupResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LookupResponse& operator=(LookupResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LookupResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const LookupResponse* internal_default_instance() {
    return reinterpret_cast<const LookupResponse*>(
               &_LookupResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(LookupResponse& a, LookupResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(LookupResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LookupResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LookupResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LookupResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LookupResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LookupResponse& from) {
    LookupResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LookupResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gluten.shard.proto.LookupResponse";
  }
  protected:
  explicit LookupResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputHitsFieldNumber = 2,
    kOutputCompactFieldNumber = 1,
  };
  // repeated int32 input_hits = 2;
  int input_hits_size() const;
  private:
  int _internal_input_hits_size() const;
  public:
  void clear_input_hits();
  private:
  int32_t _internal_input_hits(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_input_hits() const;
  void _internal_add_input_hits(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_input_hits();
  public:
  int32_t input_hits(int index) const;
  void set_input_hits(int index, int32_t value);
  void add_input_hits(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      input_hits() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_input_hits();

  // bytes output_compact = 1;
  void clear_output_compact();
  const std::string& output_compact() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_output_compact(ArgT0&& arg0, ArgT... args);
  std::string* mutable_output_compact();
  PROTOBUF_NODISCARD std::string* release_output_compact();
  void set_allocated_output_compact(std::string* output_compact);
  private:
  const std::string& _internal_output_compact() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_output_compact(const std::string& value);
  std::string* _internal_mutable_output_compact();
  public:

  // @@protoc_insertion_point(class_scope:gluten.shard.proto.LookupResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > input_hits_;
    mutable std::atomic<int> _input_hits_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr output_compact_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shard_5flookup_2eproto;
};
// -------------------------------------------------------------------

class ShardLookupEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gluten.shard.proto.ShardLookupEntry) */ {
 public:
  inline ShardLookupEntry() : ShardLookupEntry(nullptr) {}
  ~ShardLookupEntry() override;
  explicit PROTOBUF_CONSTEXPR ShardLookupEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShardLookupEntry(const ShardLookupEntry& from);
  ShardLookupEntry(ShardLookupEntry&& from) noexcept
    : ShardLookupEntry() {
    *this = ::std::move(from);
  }

  inline ShardLookupEntry& operator=(const ShardLookupEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShardLookupEntry& operator=(ShardLookupEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ShardLookupEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShardLookupEntry* internal_default_instance() {
    return reinterpret_cast<const ShardLookupEntry*>(
               &_ShardLookupEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ShardLookupEntry& a, ShardLookupEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(ShardLookupEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShardLookupEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShardLookupEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShardLookupEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ShardLookupEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ShardLookupEntry& from) {
    ShardLookupEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShardLookupEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gluten.shard.proto.ShardLookupEntry";
  }
  protected:
  explicit ShardLookupEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputIndicesFieldNumber = 3,
    kProbeKeysCompactFieldNumber = 2,
    kProbeFilterColumnsCompactFieldNumber = 4,
    kFilterExpressionFieldNumber = 5,
    kProbeColumnsTypeFieldNumber = 6,
    kFilterInputTypeFieldNumber = 7,
    kShardIdFieldNumber = 1,
  };
  // repeated int32 input_indices = 3;
  int input_indices_size() const;
  private:
  int _internal_input_indices_size() const;
  public:
  void clear_input_indices();
  private:
  int32_t _internal_input_indices(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_input_indices() const;
  void _internal_add_input_indices(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_input_indices();
  public:
  int32_t input_indices(int index) const;
  void set_input_indices(int index, int32_t value);
  void add_input_indices(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      input_indices() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_input_indices();

  // bytes probe_keys_compact = 2;
  void clear_probe_keys_compact();
  const std::string& probe_keys_compact() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_probe_keys_compact(ArgT0&& arg0, ArgT... args);
  std::string* mutable_probe_keys_compact();
  PROTOBUF_NODISCARD std::string* release_probe_keys_compact();
  void set_allocated_probe_keys_compact(std::string* probe_keys_compact);
  private:
  const std::string& _internal_probe_keys_compact() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_probe_keys_compact(const std::string& value);
  std::string* _internal_mutable_probe_keys_compact();
  public:

  // bytes probe_filter_columns_compact = 4;
  void clear_probe_filter_columns_compact();
  const std::string& probe_filter_columns_compact() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_probe_filter_columns_compact(ArgT0&& arg0, ArgT... args);
  std::string* mutable_probe_filter_columns_compact();
  PROTOBUF_NODISCARD std::string* release_probe_filter_columns_compact();
  void set_allocated_probe_filter_columns_compact(std::string* probe_filter_columns_compact);
  private:
  const std::string& _internal_probe_filter_columns_compact() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_probe_filter_columns_compact(const std::string& value);
  std::string* _internal_mutable_probe_filter_columns_compact();
  public:

  // string filter_expression = 5;
  void clear_filter_expression();
  const std::string& filter_expression() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filter_expression(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filter_expression();
  PROTOBUF_NODISCARD std::string* release_filter_expression();
  void set_allocated_filter_expression(std::string* filter_expression);
  private:
  const std::string& _internal_filter_expression() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filter_expression(const std::string& value);
  std::string* _internal_mutable_filter_expression();
  public:

  // string probe_columns_type = 6;
  void clear_probe_columns_type();
  const std::string& probe_columns_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_probe_columns_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_probe_columns_type();
  PROTOBUF_NODISCARD std::string* release_probe_columns_type();
  void set_allocated_probe_columns_type(std::string* probe_columns_type);
  private:
  const std::string& _internal_probe_columns_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_probe_columns_type(const std::string& value);
  std::string* _internal_mutable_probe_columns_type();
  public:

  // string filter_input_type = 7;
  void clear_filter_input_type();
  const std::string& filter_input_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_filter_input_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_filter_input_type();
  PROTOBUF_NODISCARD std::string* release_filter_input_type();
  void set_allocated_filter_input_type(std::string* filter_input_type);
  private:
  const std::string& _internal_filter_input_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filter_input_type(const std::string& value);
  std::string* _internal_mutable_filter_input_type();
  public:

  // int32 shard_id = 1;
  void clear_shard_id();
  int32_t shard_id() const;
  void set_shard_id(int32_t value);
  private:
  int32_t _internal_shard_id() const;
  void _internal_set_shard_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:gluten.shard.proto.ShardLookupEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > input_indices_;
    mutable std::atomic<int> _input_indices_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr probe_keys_compact_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr probe_filter_columns_compact_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filter_expression_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr probe_columns_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filter_input_type_;
    int32_t shard_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shard_5flookup_2eproto;
};
// -------------------------------------------------------------------

class ShardLookupResultEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gluten.shard.proto.ShardLookupResultEntry) */ {
 public:
  inline ShardLookupResultEntry() : ShardLookupResultEntry(nullptr) {}
  ~ShardLookupResultEntry() override;
  explicit PROTOBUF_CONSTEXPR ShardLookupResultEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShardLookupResultEntry(const ShardLookupResultEntry& from);
  ShardLookupResultEntry(ShardLookupResultEntry&& from) noexcept
    : ShardLookupResultEntry() {
    *this = ::std::move(from);
  }

  inline ShardLookupResultEntry& operator=(const ShardLookupResultEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShardLookupResultEntry& operator=(ShardLookupResultEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ShardLookupResultEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShardLookupResultEntry* internal_default_instance() {
    return reinterpret_cast<const ShardLookupResultEntry*>(
               &_ShardLookupResultEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ShardLookupResultEntry& a, ShardLookupResultEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(ShardLookupResultEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShardLookupResultEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShardLookupResultEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShardLookupResultEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ShardLookupResultEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ShardLookupResultEntry& from) {
    ShardLookupResultEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShardLookupResultEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gluten.shard.proto.ShardLookupResultEntry";
  }
  protected:
  explicit ShardLookupResultEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInputHitsFieldNumber = 3,
    kOutputCompactFieldNumber = 2,
    kShardIdFieldNumber = 1,
  };
  // repeated int32 input_hits = 3;
  int input_hits_size() const;
  private:
  int _internal_input_hits_size() const;
  public:
  void clear_input_hits();
  private:
  int32_t _internal_input_hits(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_input_hits() const;
  void _internal_add_input_hits(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_input_hits();
  public:
  int32_t input_hits(int index) const;
  void set_input_hits(int index, int32_t value);
  void add_input_hits(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      input_hits() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_input_hits();

  // bytes output_compact = 2;
  void clear_output_compact();
  const std::string& output_compact() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_output_compact(ArgT0&& arg0, ArgT... args);
  std::string* mutable_output_compact();
  PROTOBUF_NODISCARD std::string* release_output_compact();
  void set_allocated_output_compact(std::string* output_compact);
  private:
  const std::string& _internal_output_compact() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_output_compact(const std::string& value);
  std::string* _internal_mutable_output_compact();
  public:

  // int32 shard_id = 1;
  void clear_shard_id();
  int32_t shard_id() const;
  void set_shard_id(int32_t value);
  private:
  int32_t _internal_shard_id() const;
  void _internal_set_shard_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:gluten.shard.proto.ShardLookupResultEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > input_hits_;
    mutable std::atomic<int> _input_hits_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr output_compact_;
    int32_t shard_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shard_5flookup_2eproto;
};
// -------------------------------------------------------------------

class BatchLookupRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gluten.shard.proto.BatchLookupRequest) */ {
 public:
  inline BatchLookupRequest() : BatchLookupRequest(nullptr) {}
  ~BatchLookupRequest() override;
  explicit PROTOBUF_CONSTEXPR BatchLookupRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BatchLookupRequest(const BatchLookupRequest& from);
  BatchLookupRequest(BatchLookupRequest&& from) noexcept
    : BatchLookupRequest() {
    *this = ::std::move(from);
  }

  inline BatchLookupRequest& operator=(const BatchLookupRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BatchLookupRequest& operator=(BatchLookupRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BatchLookupRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BatchLookupRequest* internal_default_instance() {
    return reinterpret_cast<const BatchLookupRequest*>(
               &_BatchLookupRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(BatchLookupRequest& a, BatchLookupRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(BatchLookupRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BatchLookupRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BatchLookupRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BatchLookupRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BatchLookupRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BatchLookupRequest& from) {
    BatchLookupRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BatchLookupRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gluten.shard.proto.BatchLookupRequest";
  }
  protected:
  explicit BatchLookupRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntriesFieldNumber = 2,
    kSetIdFieldNumber = 1,
  };
  // repeated .gluten.shard.proto.ShardLookupEntry entries = 2;
  int entries_size() const;
  private:
  int _internal_entries_size() const;
  public:
  void clear_entries();
  ::gluten::shard::proto::ShardLookupEntry* mutable_entries(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gluten::shard::proto::ShardLookupEntry >*
      mutable_entries();
  private:
  const ::gluten::shard::proto::ShardLookupEntry& _internal_entries(int index) const;
  ::gluten::shard::proto::ShardLookupEntry* _internal_add_entries();
  public:
  const ::gluten::shard::proto::ShardLookupEntry& entries(int index) const;
  ::gluten::shard::proto::ShardLookupEntry* add_entries();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gluten::shard::proto::ShardLookupEntry >&
      entries() const;

  // int64 set_id = 1;
  void clear_set_id();
  int64_t set_id() const;
  void set_set_id(int64_t value);
  private:
  int64_t _internal_set_id() const;
  void _internal_set_set_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:gluten.shard.proto.BatchLookupRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gluten::shard::proto::ShardLookupEntry > entries_;
    int64_t set_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shard_5flookup_2eproto;
};
// -------------------------------------------------------------------

class BatchLookupResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gluten.shard.proto.BatchLookupResponse) */ {
 public:
  inline BatchLookupResponse() : BatchLookupResponse(nullptr) {}
  ~BatchLookupResponse() override;
  explicit PROTOBUF_CONSTEXPR BatchLookupResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BatchLookupResponse(const BatchLookupResponse& from);
  BatchLookupResponse(BatchLookupResponse&& from) noexcept
    : BatchLookupResponse() {
    *this = ::std::move(from);
  }

  inline BatchLookupResponse& operator=(const BatchLookupResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BatchLookupResponse& operator=(BatchLookupResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BatchLookupResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BatchLookupResponse* internal_default_instance() {
    return reinterpret_cast<const BatchLookupResponse*>(
               &_BatchLookupResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(BatchLookupResponse& a, BatchLookupResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BatchLookupResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BatchLookupResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BatchLookupResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BatchLookupResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BatchLookupResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BatchLookupResponse& from) {
    BatchLookupResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BatchLookupResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gluten.shard.proto.BatchLookupResponse";
  }
  protected:
  explicit BatchLookupResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultsFieldNumber = 1,
  };
  // repeated .gluten.shard.proto.ShardLookupResultEntry results = 1;
  int results_size() const;
  private:
  int _internal_results_size() const;
  public:
  void clear_results();
  ::gluten::shard::proto::ShardLookupResultEntry* mutable_results(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gluten::shard::proto::ShardLookupResultEntry >*
      mutable_results();
  private:
  const ::gluten::shard::proto::ShardLookupResultEntry& _internal_results(int index) const;
  ::gluten::shard::proto::ShardLookupResultEntry* _internal_add_results();
  public:
  const ::gluten::shard::proto::ShardLookupResultEntry& results(int index) const;
  ::gluten::shard::proto::ShardLookupResultEntry* add_results();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gluten::shard::proto::ShardLookupResultEntry >&
      results() const;

  // @@protoc_insertion_point(class_scope:gluten.shard.proto.BatchLookupResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gluten::shard::proto::ShardLookupResultEntry > results_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shard_5flookup_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LookupRequest

// int64 set_id = 1;
inline void LookupRequest::clear_set_id() {
  _impl_.set_id_ = int64_t{0};
}
inline int64_t LookupRequest::_internal_set_id() const {
  return _impl_.set_id_;
}
inline int64_t LookupRequest::set_id() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.LookupRequest.set_id)
  return _internal_set_id();
}
inline void LookupRequest::_internal_set_set_id(int64_t value) {
  
  _impl_.set_id_ = value;
}
inline void LookupRequest::set_set_id(int64_t value) {
  _internal_set_set_id(value);
  // @@protoc_insertion_point(field_set:gluten.shard.proto.LookupRequest.set_id)
}

// int32 shard_id = 2;
inline void LookupRequest::clear_shard_id() {
  _impl_.shard_id_ = 0;
}
inline int32_t LookupRequest::_internal_shard_id() const {
  return _impl_.shard_id_;
}
inline int32_t LookupRequest::shard_id() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.LookupRequest.shard_id)
  return _internal_shard_id();
}
inline void LookupRequest::_internal_set_shard_id(int32_t value) {
  
  _impl_.shard_id_ = value;
}
inline void LookupRequest::set_shard_id(int32_t value) {
  _internal_set_shard_id(value);
  // @@protoc_insertion_point(field_set:gluten.shard.proto.LookupRequest.shard_id)
}

// bytes probe_keys_compact = 3;
inline void LookupRequest::clear_probe_keys_compact() {
  _impl_.probe_keys_compact_.ClearToEmpty();
}
inline const std::string& LookupRequest::probe_keys_compact() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.LookupRequest.probe_keys_compact)
  return _internal_probe_keys_compact();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LookupRequest::set_probe_keys_compact(ArgT0&& arg0, ArgT... args) {
 
 _impl_.probe_keys_compact_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.LookupRequest.probe_keys_compact)
}
inline std::string* LookupRequest::mutable_probe_keys_compact() {
  std::string* _s = _internal_mutable_probe_keys_compact();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.LookupRequest.probe_keys_compact)
  return _s;
}
inline const std::string& LookupRequest::_internal_probe_keys_compact() const {
  return _impl_.probe_keys_compact_.Get();
}
inline void LookupRequest::_internal_set_probe_keys_compact(const std::string& value) {
  
  _impl_.probe_keys_compact_.Set(value, GetArenaForAllocation());
}
inline std::string* LookupRequest::_internal_mutable_probe_keys_compact() {
  
  return _impl_.probe_keys_compact_.Mutable(GetArenaForAllocation());
}
inline std::string* LookupRequest::release_probe_keys_compact() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.LookupRequest.probe_keys_compact)
  return _impl_.probe_keys_compact_.Release();
}
inline void LookupRequest::set_allocated_probe_keys_compact(std::string* probe_keys_compact) {
  if (probe_keys_compact != nullptr) {
    
  } else {
    
  }
  _impl_.probe_keys_compact_.SetAllocated(probe_keys_compact, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.probe_keys_compact_.IsDefault()) {
    _impl_.probe_keys_compact_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.LookupRequest.probe_keys_compact)
}

// repeated int32 input_indices = 4;
inline int LookupRequest::_internal_input_indices_size() const {
  return _impl_.input_indices_.size();
}
inline int LookupRequest::input_indices_size() const {
  return _internal_input_indices_size();
}
inline void LookupRequest::clear_input_indices() {
  _impl_.input_indices_.Clear();
}
inline int32_t LookupRequest::_internal_input_indices(int index) const {
  return _impl_.input_indices_.Get(index);
}
inline int32_t LookupRequest::input_indices(int index) const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.LookupRequest.input_indices)
  return _internal_input_indices(index);
}
inline void LookupRequest::set_input_indices(int index, int32_t value) {
  _impl_.input_indices_.Set(index, value);
  // @@protoc_insertion_point(field_set:gluten.shard.proto.LookupRequest.input_indices)
}
inline void LookupRequest::_internal_add_input_indices(int32_t value) {
  _impl_.input_indices_.Add(value);
}
inline void LookupRequest::add_input_indices(int32_t value) {
  _internal_add_input_indices(value);
  // @@protoc_insertion_point(field_add:gluten.shard.proto.LookupRequest.input_indices)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
LookupRequest::_internal_input_indices() const {
  return _impl_.input_indices_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
LookupRequest::input_indices() const {
  // @@protoc_insertion_point(field_list:gluten.shard.proto.LookupRequest.input_indices)
  return _internal_input_indices();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
LookupRequest::_internal_mutable_input_indices() {
  return &_impl_.input_indices_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
LookupRequest::mutable_input_indices() {
  // @@protoc_insertion_point(field_mutable_list:gluten.shard.proto.LookupRequest.input_indices)
  return _internal_mutable_input_indices();
}

// bytes probe_filter_columns_compact = 5;
inline void LookupRequest::clear_probe_filter_columns_compact() {
  _impl_.probe_filter_columns_compact_.ClearToEmpty();
}
inline const std::string& LookupRequest::probe_filter_columns_compact() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.LookupRequest.probe_filter_columns_compact)
  return _internal_probe_filter_columns_compact();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LookupRequest::set_probe_filter_columns_compact(ArgT0&& arg0, ArgT... args) {
 
 _impl_.probe_filter_columns_compact_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.LookupRequest.probe_filter_columns_compact)
}
inline std::string* LookupRequest::mutable_probe_filter_columns_compact() {
  std::string* _s = _internal_mutable_probe_filter_columns_compact();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.LookupRequest.probe_filter_columns_compact)
  return _s;
}
inline const std::string& LookupRequest::_internal_probe_filter_columns_compact() const {
  return _impl_.probe_filter_columns_compact_.Get();
}
inline void LookupRequest::_internal_set_probe_filter_columns_compact(const std::string& value) {
  
  _impl_.probe_filter_columns_compact_.Set(value, GetArenaForAllocation());
}
inline std::string* LookupRequest::_internal_mutable_probe_filter_columns_compact() {
  
  return _impl_.probe_filter_columns_compact_.Mutable(GetArenaForAllocation());
}
inline std::string* LookupRequest::release_probe_filter_columns_compact() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.LookupRequest.probe_filter_columns_compact)
  return _impl_.probe_filter_columns_compact_.Release();
}
inline void LookupRequest::set_allocated_probe_filter_columns_compact(std::string* probe_filter_columns_compact) {
  if (probe_filter_columns_compact != nullptr) {
    
  } else {
    
  }
  _impl_.probe_filter_columns_compact_.SetAllocated(probe_filter_columns_compact, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.probe_filter_columns_compact_.IsDefault()) {
    _impl_.probe_filter_columns_compact_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.LookupRequest.probe_filter_columns_compact)
}

// string filter_expression = 6;
inline void LookupRequest::clear_filter_expression() {
  _impl_.filter_expression_.ClearToEmpty();
}
inline const std::string& LookupRequest::filter_expression() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.LookupRequest.filter_expression)
  return _internal_filter_expression();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LookupRequest::set_filter_expression(ArgT0&& arg0, ArgT... args) {
 
 _impl_.filter_expression_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.LookupRequest.filter_expression)
}
inline std::string* LookupRequest::mutable_filter_expression() {
  std::string* _s = _internal_mutable_filter_expression();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.LookupRequest.filter_expression)
  return _s;
}
inline const std::string& LookupRequest::_internal_filter_expression() const {
  return _impl_.filter_expression_.Get();
}
inline void LookupRequest::_internal_set_filter_expression(const std::string& value) {
  
  _impl_.filter_expression_.Set(value, GetArenaForAllocation());
}
inline std::string* LookupRequest::_internal_mutable_filter_expression() {
  
  return _impl_.filter_expression_.Mutable(GetArenaForAllocation());
}
inline std::string* LookupRequest::release_filter_expression() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.LookupRequest.filter_expression)
  return _impl_.filter_expression_.Release();
}
inline void LookupRequest::set_allocated_filter_expression(std::string* filter_expression) {
  if (filter_expression != nullptr) {
    
  } else {
    
  }
  _impl_.filter_expression_.SetAllocated(filter_expression, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filter_expression_.IsDefault()) {
    _impl_.filter_expression_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.LookupRequest.filter_expression)
}

// string probe_columns_type = 7;
inline void LookupRequest::clear_probe_columns_type() {
  _impl_.probe_columns_type_.ClearToEmpty();
}
inline const std::string& LookupRequest::probe_columns_type() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.LookupRequest.probe_columns_type)
  return _internal_probe_columns_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LookupRequest::set_probe_columns_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.probe_columns_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.LookupRequest.probe_columns_type)
}
inline std::string* LookupRequest::mutable_probe_columns_type() {
  std::string* _s = _internal_mutable_probe_columns_type();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.LookupRequest.probe_columns_type)
  return _s;
}
inline const std::string& LookupRequest::_internal_probe_columns_type() const {
  return _impl_.probe_columns_type_.Get();
}
inline void LookupRequest::_internal_set_probe_columns_type(const std::string& value) {
  
  _impl_.probe_columns_type_.Set(value, GetArenaForAllocation());
}
inline std::string* LookupRequest::_internal_mutable_probe_columns_type() {
  
  return _impl_.probe_columns_type_.Mutable(GetArenaForAllocation());
}
inline std::string* LookupRequest::release_probe_columns_type() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.LookupRequest.probe_columns_type)
  return _impl_.probe_columns_type_.Release();
}
inline void LookupRequest::set_allocated_probe_columns_type(std::string* probe_columns_type) {
  if (probe_columns_type != nullptr) {
    
  } else {
    
  }
  _impl_.probe_columns_type_.SetAllocated(probe_columns_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.probe_columns_type_.IsDefault()) {
    _impl_.probe_columns_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.LookupRequest.probe_columns_type)
}

// string filter_input_type = 8;
inline void LookupRequest::clear_filter_input_type() {
  _impl_.filter_input_type_.ClearToEmpty();
}
inline const std::string& LookupRequest::filter_input_type() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.LookupRequest.filter_input_type)
  return _internal_filter_input_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LookupRequest::set_filter_input_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.filter_input_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.LookupRequest.filter_input_type)
}
inline std::string* LookupRequest::mutable_filter_input_type() {
  std::string* _s = _internal_mutable_filter_input_type();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.LookupRequest.filter_input_type)
  return _s;
}
inline const std::string& LookupRequest::_internal_filter_input_type() const {
  return _impl_.filter_input_type_.Get();
}
inline void LookupRequest::_internal_set_filter_input_type(const std::string& value) {
  
  _impl_.filter_input_type_.Set(value, GetArenaForAllocation());
}
inline std::string* LookupRequest::_internal_mutable_filter_input_type() {
  
  return _impl_.filter_input_type_.Mutable(GetArenaForAllocation());
}
inline std::string* LookupRequest::release_filter_input_type() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.LookupRequest.filter_input_type)
  return _impl_.filter_input_type_.Release();
}
inline void LookupRequest::set_allocated_filter_input_type(std::string* filter_input_type) {
  if (filter_input_type != nullptr) {
    
  } else {
    
  }
  _impl_.filter_input_type_.SetAllocated(filter_input_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filter_input_type_.IsDefault()) {
    _impl_.filter_input_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.LookupRequest.filter_input_type)
}

// -------------------------------------------------------------------

// LookupResponse

// bytes output_compact = 1;
inline void LookupResponse::clear_output_compact() {
  _impl_.output_compact_.ClearToEmpty();
}
inline const std::string& LookupResponse::output_compact() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.LookupResponse.output_compact)
  return _internal_output_compact();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void LookupResponse::set_output_compact(ArgT0&& arg0, ArgT... args) {
 
 _impl_.output_compact_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.LookupResponse.output_compact)
}
inline std::string* LookupResponse::mutable_output_compact() {
  std::string* _s = _internal_mutable_output_compact();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.LookupResponse.output_compact)
  return _s;
}
inline const std::string& LookupResponse::_internal_output_compact() const {
  return _impl_.output_compact_.Get();
}
inline void LookupResponse::_internal_set_output_compact(const std::string& value) {
  
  _impl_.output_compact_.Set(value, GetArenaForAllocation());
}
inline std::string* LookupResponse::_internal_mutable_output_compact() {
  
  return _impl_.output_compact_.Mutable(GetArenaForAllocation());
}
inline std::string* LookupResponse::release_output_compact() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.LookupResponse.output_compact)
  return _impl_.output_compact_.Release();
}
inline void LookupResponse::set_allocated_output_compact(std::string* output_compact) {
  if (output_compact != nullptr) {
    
  } else {
    
  }
  _impl_.output_compact_.SetAllocated(output_compact, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.output_compact_.IsDefault()) {
    _impl_.output_compact_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.LookupResponse.output_compact)
}

// repeated int32 input_hits = 2;
inline int LookupResponse::_internal_input_hits_size() const {
  return _impl_.input_hits_.size();
}
inline int LookupResponse::input_hits_size() const {
  return _internal_input_hits_size();
}
inline void LookupResponse::clear_input_hits() {
  _impl_.input_hits_.Clear();
}
inline int32_t LookupResponse::_internal_input_hits(int index) const {
  return _impl_.input_hits_.Get(index);
}
inline int32_t LookupResponse::input_hits(int index) const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.LookupResponse.input_hits)
  return _internal_input_hits(index);
}
inline void LookupResponse::set_input_hits(int index, int32_t value) {
  _impl_.input_hits_.Set(index, value);
  // @@protoc_insertion_point(field_set:gluten.shard.proto.LookupResponse.input_hits)
}
inline void LookupResponse::_internal_add_input_hits(int32_t value) {
  _impl_.input_hits_.Add(value);
}
inline void LookupResponse::add_input_hits(int32_t value) {
  _internal_add_input_hits(value);
  // @@protoc_insertion_point(field_add:gluten.shard.proto.LookupResponse.input_hits)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
LookupResponse::_internal_input_hits() const {
  return _impl_.input_hits_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
LookupResponse::input_hits() const {
  // @@protoc_insertion_point(field_list:gluten.shard.proto.LookupResponse.input_hits)
  return _internal_input_hits();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
LookupResponse::_internal_mutable_input_hits() {
  return &_impl_.input_hits_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
LookupResponse::mutable_input_hits() {
  // @@protoc_insertion_point(field_mutable_list:gluten.shard.proto.LookupResponse.input_hits)
  return _internal_mutable_input_hits();
}

// -------------------------------------------------------------------

// ShardLookupEntry

// int32 shard_id = 1;
inline void ShardLookupEntry::clear_shard_id() {
  _impl_.shard_id_ = 0;
}
inline int32_t ShardLookupEntry::_internal_shard_id() const {
  return _impl_.shard_id_;
}
inline int32_t ShardLookupEntry::shard_id() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.ShardLookupEntry.shard_id)
  return _internal_shard_id();
}
inline void ShardLookupEntry::_internal_set_shard_id(int32_t value) {
  
  _impl_.shard_id_ = value;
}
inline void ShardLookupEntry::set_shard_id(int32_t value) {
  _internal_set_shard_id(value);
  // @@protoc_insertion_point(field_set:gluten.shard.proto.ShardLookupEntry.shard_id)
}

// bytes probe_keys_compact = 2;
inline void ShardLookupEntry::clear_probe_keys_compact() {
  _impl_.probe_keys_compact_.ClearToEmpty();
}
inline const std::string& ShardLookupEntry::probe_keys_compact() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.ShardLookupEntry.probe_keys_compact)
  return _internal_probe_keys_compact();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShardLookupEntry::set_probe_keys_compact(ArgT0&& arg0, ArgT... args) {
 
 _impl_.probe_keys_compact_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.ShardLookupEntry.probe_keys_compact)
}
inline std::string* ShardLookupEntry::mutable_probe_keys_compact() {
  std::string* _s = _internal_mutable_probe_keys_compact();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.ShardLookupEntry.probe_keys_compact)
  return _s;
}
inline const std::string& ShardLookupEntry::_internal_probe_keys_compact() const {
  return _impl_.probe_keys_compact_.Get();
}
inline void ShardLookupEntry::_internal_set_probe_keys_compact(const std::string& value) {
  
  _impl_.probe_keys_compact_.Set(value, GetArenaForAllocation());
}
inline std::string* ShardLookupEntry::_internal_mutable_probe_keys_compact() {
  
  return _impl_.probe_keys_compact_.Mutable(GetArenaForAllocation());
}
inline std::string* ShardLookupEntry::release_probe_keys_compact() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.ShardLookupEntry.probe_keys_compact)
  return _impl_.probe_keys_compact_.Release();
}
inline void ShardLookupEntry::set_allocated_probe_keys_compact(std::string* probe_keys_compact) {
  if (probe_keys_compact != nullptr) {
    
  } else {
    
  }
  _impl_.probe_keys_compact_.SetAllocated(probe_keys_compact, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.probe_keys_compact_.IsDefault()) {
    _impl_.probe_keys_compact_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.ShardLookupEntry.probe_keys_compact)
}

// repeated int32 input_indices = 3;
inline int ShardLookupEntry::_internal_input_indices_size() const {
  return _impl_.input_indices_.size();
}
inline int ShardLookupEntry::input_indices_size() const {
  return _internal_input_indices_size();
}
inline void ShardLookupEntry::clear_input_indices() {
  _impl_.input_indices_.Clear();
}
inline int32_t ShardLookupEntry::_internal_input_indices(int index) const {
  return _impl_.input_indices_.Get(index);
}
inline int32_t ShardLookupEntry::input_indices(int index) const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.ShardLookupEntry.input_indices)
  return _internal_input_indices(index);
}
inline void ShardLookupEntry::set_input_indices(int index, int32_t value) {
  _impl_.input_indices_.Set(index, value);
  // @@protoc_insertion_point(field_set:gluten.shard.proto.ShardLookupEntry.input_indices)
}
inline void ShardLookupEntry::_internal_add_input_indices(int32_t value) {
  _impl_.input_indices_.Add(value);
}
inline void ShardLookupEntry::add_input_indices(int32_t value) {
  _internal_add_input_indices(value);
  // @@protoc_insertion_point(field_add:gluten.shard.proto.ShardLookupEntry.input_indices)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
ShardLookupEntry::_internal_input_indices() const {
  return _impl_.input_indices_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
ShardLookupEntry::input_indices() const {
  // @@protoc_insertion_point(field_list:gluten.shard.proto.ShardLookupEntry.input_indices)
  return _internal_input_indices();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
ShardLookupEntry::_internal_mutable_input_indices() {
  return &_impl_.input_indices_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
ShardLookupEntry::mutable_input_indices() {
  // @@protoc_insertion_point(field_mutable_list:gluten.shard.proto.ShardLookupEntry.input_indices)
  return _internal_mutable_input_indices();
}

// bytes probe_filter_columns_compact = 4;
inline void ShardLookupEntry::clear_probe_filter_columns_compact() {
  _impl_.probe_filter_columns_compact_.ClearToEmpty();
}
inline const std::string& ShardLookupEntry::probe_filter_columns_compact() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.ShardLookupEntry.probe_filter_columns_compact)
  return _internal_probe_filter_columns_compact();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShardLookupEntry::set_probe_filter_columns_compact(ArgT0&& arg0, ArgT... args) {
 
 _impl_.probe_filter_columns_compact_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.ShardLookupEntry.probe_filter_columns_compact)
}
inline std::string* ShardLookupEntry::mutable_probe_filter_columns_compact() {
  std::string* _s = _internal_mutable_probe_filter_columns_compact();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.ShardLookupEntry.probe_filter_columns_compact)
  return _s;
}
inline const std::string& ShardLookupEntry::_internal_probe_filter_columns_compact() const {
  return _impl_.probe_filter_columns_compact_.Get();
}
inline void ShardLookupEntry::_internal_set_probe_filter_columns_compact(const std::string& value) {
  
  _impl_.probe_filter_columns_compact_.Set(value, GetArenaForAllocation());
}
inline std::string* ShardLookupEntry::_internal_mutable_probe_filter_columns_compact() {
  
  return _impl_.probe_filter_columns_compact_.Mutable(GetArenaForAllocation());
}
inline std::string* ShardLookupEntry::release_probe_filter_columns_compact() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.ShardLookupEntry.probe_filter_columns_compact)
  return _impl_.probe_filter_columns_compact_.Release();
}
inline void ShardLookupEntry::set_allocated_probe_filter_columns_compact(std::string* probe_filter_columns_compact) {
  if (probe_filter_columns_compact != nullptr) {
    
  } else {
    
  }
  _impl_.probe_filter_columns_compact_.SetAllocated(probe_filter_columns_compact, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.probe_filter_columns_compact_.IsDefault()) {
    _impl_.probe_filter_columns_compact_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.ShardLookupEntry.probe_filter_columns_compact)
}

// string filter_expression = 5;
inline void ShardLookupEntry::clear_filter_expression() {
  _impl_.filter_expression_.ClearToEmpty();
}
inline const std::string& ShardLookupEntry::filter_expression() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.ShardLookupEntry.filter_expression)
  return _internal_filter_expression();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShardLookupEntry::set_filter_expression(ArgT0&& arg0, ArgT... args) {
 
 _impl_.filter_expression_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.ShardLookupEntry.filter_expression)
}
inline std::string* ShardLookupEntry::mutable_filter_expression() {
  std::string* _s = _internal_mutable_filter_expression();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.ShardLookupEntry.filter_expression)
  return _s;
}
inline const std::string& ShardLookupEntry::_internal_filter_expression() const {
  return _impl_.filter_expression_.Get();
}
inline void ShardLookupEntry::_internal_set_filter_expression(const std::string& value) {
  
  _impl_.filter_expression_.Set(value, GetArenaForAllocation());
}
inline std::string* ShardLookupEntry::_internal_mutable_filter_expression() {
  
  return _impl_.filter_expression_.Mutable(GetArenaForAllocation());
}
inline std::string* ShardLookupEntry::release_filter_expression() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.ShardLookupEntry.filter_expression)
  return _impl_.filter_expression_.Release();
}
inline void ShardLookupEntry::set_allocated_filter_expression(std::string* filter_expression) {
  if (filter_expression != nullptr) {
    
  } else {
    
  }
  _impl_.filter_expression_.SetAllocated(filter_expression, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filter_expression_.IsDefault()) {
    _impl_.filter_expression_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.ShardLookupEntry.filter_expression)
}

// string probe_columns_type = 6;
inline void ShardLookupEntry::clear_probe_columns_type() {
  _impl_.probe_columns_type_.ClearToEmpty();
}
inline const std::string& ShardLookupEntry::probe_columns_type() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.ShardLookupEntry.probe_columns_type)
  return _internal_probe_columns_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShardLookupEntry::set_probe_columns_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.probe_columns_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.ShardLookupEntry.probe_columns_type)
}
inline std::string* ShardLookupEntry::mutable_probe_columns_type() {
  std::string* _s = _internal_mutable_probe_columns_type();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.ShardLookupEntry.probe_columns_type)
  return _s;
}
inline const std::string& ShardLookupEntry::_internal_probe_columns_type() const {
  return _impl_.probe_columns_type_.Get();
}
inline void ShardLookupEntry::_internal_set_probe_columns_type(const std::string& value) {
  
  _impl_.probe_columns_type_.Set(value, GetArenaForAllocation());
}
inline std::string* ShardLookupEntry::_internal_mutable_probe_columns_type() {
  
  return _impl_.probe_columns_type_.Mutable(GetArenaForAllocation());
}
inline std::string* ShardLookupEntry::release_probe_columns_type() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.ShardLookupEntry.probe_columns_type)
  return _impl_.probe_columns_type_.Release();
}
inline void ShardLookupEntry::set_allocated_probe_columns_type(std::string* probe_columns_type) {
  if (probe_columns_type != nullptr) {
    
  } else {
    
  }
  _impl_.probe_columns_type_.SetAllocated(probe_columns_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.probe_columns_type_.IsDefault()) {
    _impl_.probe_columns_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.ShardLookupEntry.probe_columns_type)
}

// string filter_input_type = 7;
inline void ShardLookupEntry::clear_filter_input_type() {
  _impl_.filter_input_type_.ClearToEmpty();
}
inline const std::string& ShardLookupEntry::filter_input_type() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.ShardLookupEntry.filter_input_type)
  return _internal_filter_input_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShardLookupEntry::set_filter_input_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.filter_input_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.ShardLookupEntry.filter_input_type)
}
inline std::string* ShardLookupEntry::mutable_filter_input_type() {
  std::string* _s = _internal_mutable_filter_input_type();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.ShardLookupEntry.filter_input_type)
  return _s;
}
inline const std::string& ShardLookupEntry::_internal_filter_input_type() const {
  return _impl_.filter_input_type_.Get();
}
inline void ShardLookupEntry::_internal_set_filter_input_type(const std::string& value) {
  
  _impl_.filter_input_type_.Set(value, GetArenaForAllocation());
}
inline std::string* ShardLookupEntry::_internal_mutable_filter_input_type() {
  
  return _impl_.filter_input_type_.Mutable(GetArenaForAllocation());
}
inline std::string* ShardLookupEntry::release_filter_input_type() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.ShardLookupEntry.filter_input_type)
  return _impl_.filter_input_type_.Release();
}
inline void ShardLookupEntry::set_allocated_filter_input_type(std::string* filter_input_type) {
  if (filter_input_type != nullptr) {
    
  } else {
    
  }
  _impl_.filter_input_type_.SetAllocated(filter_input_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.filter_input_type_.IsDefault()) {
    _impl_.filter_input_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.ShardLookupEntry.filter_input_type)
}

// -------------------------------------------------------------------

// ShardLookupResultEntry

// int32 shard_id = 1;
inline void ShardLookupResultEntry::clear_shard_id() {
  _impl_.shard_id_ = 0;
}
inline int32_t ShardLookupResultEntry::_internal_shard_id() const {
  return _impl_.shard_id_;
}
inline int32_t ShardLookupResultEntry::shard_id() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.ShardLookupResultEntry.shard_id)
  return _internal_shard_id();
}
inline void ShardLookupResultEntry::_internal_set_shard_id(int32_t value) {
  
  _impl_.shard_id_ = value;
}
inline void ShardLookupResultEntry::set_shard_id(int32_t value) {
  _internal_set_shard_id(value);
  // @@protoc_insertion_point(field_set:gluten.shard.proto.ShardLookupResultEntry.shard_id)
}

// bytes output_compact = 2;
inline void ShardLookupResultEntry::clear_output_compact() {
  _impl_.output_compact_.ClearToEmpty();
}
inline const std::string& ShardLookupResultEntry::output_compact() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.ShardLookupResultEntry.output_compact)
  return _internal_output_compact();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShardLookupResultEntry::set_output_compact(ArgT0&& arg0, ArgT... args) {
 
 _impl_.output_compact_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gluten.shard.proto.ShardLookupResultEntry.output_compact)
}
inline std::string* ShardLookupResultEntry::mutable_output_compact() {
  std::string* _s = _internal_mutable_output_compact();
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.ShardLookupResultEntry.output_compact)
  return _s;
}
inline const std::string& ShardLookupResultEntry::_internal_output_compact() const {
  return _impl_.output_compact_.Get();
}
inline void ShardLookupResultEntry::_internal_set_output_compact(const std::string& value) {
  
  _impl_.output_compact_.Set(value, GetArenaForAllocation());
}
inline std::string* ShardLookupResultEntry::_internal_mutable_output_compact() {
  
  return _impl_.output_compact_.Mutable(GetArenaForAllocation());
}
inline std::string* ShardLookupResultEntry::release_output_compact() {
  // @@protoc_insertion_point(field_release:gluten.shard.proto.ShardLookupResultEntry.output_compact)
  return _impl_.output_compact_.Release();
}
inline void ShardLookupResultEntry::set_allocated_output_compact(std::string* output_compact) {
  if (output_compact != nullptr) {
    
  } else {
    
  }
  _impl_.output_compact_.SetAllocated(output_compact, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.output_compact_.IsDefault()) {
    _impl_.output_compact_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gluten.shard.proto.ShardLookupResultEntry.output_compact)
}

// repeated int32 input_hits = 3;
inline int ShardLookupResultEntry::_internal_input_hits_size() const {
  return _impl_.input_hits_.size();
}
inline int ShardLookupResultEntry::input_hits_size() const {
  return _internal_input_hits_size();
}
inline void ShardLookupResultEntry::clear_input_hits() {
  _impl_.input_hits_.Clear();
}
inline int32_t ShardLookupResultEntry::_internal_input_hits(int index) const {
  return _impl_.input_hits_.Get(index);
}
inline int32_t ShardLookupResultEntry::input_hits(int index) const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.ShardLookupResultEntry.input_hits)
  return _internal_input_hits(index);
}
inline void ShardLookupResultEntry::set_input_hits(int index, int32_t value) {
  _impl_.input_hits_.Set(index, value);
  // @@protoc_insertion_point(field_set:gluten.shard.proto.ShardLookupResultEntry.input_hits)
}
inline void ShardLookupResultEntry::_internal_add_input_hits(int32_t value) {
  _impl_.input_hits_.Add(value);
}
inline void ShardLookupResultEntry::add_input_hits(int32_t value) {
  _internal_add_input_hits(value);
  // @@protoc_insertion_point(field_add:gluten.shard.proto.ShardLookupResultEntry.input_hits)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
ShardLookupResultEntry::_internal_input_hits() const {
  return _impl_.input_hits_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
ShardLookupResultEntry::input_hits() const {
  // @@protoc_insertion_point(field_list:gluten.shard.proto.ShardLookupResultEntry.input_hits)
  return _internal_input_hits();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
ShardLookupResultEntry::_internal_mutable_input_hits() {
  return &_impl_.input_hits_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
ShardLookupResultEntry::mutable_input_hits() {
  // @@protoc_insertion_point(field_mutable_list:gluten.shard.proto.ShardLookupResultEntry.input_hits)
  return _internal_mutable_input_hits();
}

// -------------------------------------------------------------------

// BatchLookupRequest

// int64 set_id = 1;
inline void BatchLookupRequest::clear_set_id() {
  _impl_.set_id_ = int64_t{0};
}
inline int64_t BatchLookupRequest::_internal_set_id() const {
  return _impl_.set_id_;
}
inline int64_t BatchLookupRequest::set_id() const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.BatchLookupRequest.set_id)
  return _internal_set_id();
}
inline void BatchLookupRequest::_internal_set_set_id(int64_t value) {
  
  _impl_.set_id_ = value;
}
inline void BatchLookupRequest::set_set_id(int64_t value) {
  _internal_set_set_id(value);
  // @@protoc_insertion_point(field_set:gluten.shard.proto.BatchLookupRequest.set_id)
}

// repeated .gluten.shard.proto.ShardLookupEntry entries = 2;
inline int BatchLookupRequest::_internal_entries_size() const {
  return _impl_.entries_.size();
}
inline int BatchLookupRequest::entries_size() const {
  return _internal_entries_size();
}
inline void BatchLookupRequest::clear_entries() {
  _impl_.entries_.Clear();
}
inline ::gluten::shard::proto::ShardLookupEntry* BatchLookupRequest::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.BatchLookupRequest.entries)
  return _impl_.entries_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gluten::shard::proto::ShardLookupEntry >*
BatchLookupRequest::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:gluten.shard.proto.BatchLookupRequest.entries)
  return &_impl_.entries_;
}
inline const ::gluten::shard::proto::ShardLookupEntry& BatchLookupRequest::_internal_entries(int index) const {
  return _impl_.entries_.Get(index);
}
inline const ::gluten::shard::proto::ShardLookupEntry& BatchLookupRequest::entries(int index) const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.BatchLookupRequest.entries)
  return _internal_entries(index);
}
inline ::gluten::shard::proto::ShardLookupEntry* BatchLookupRequest::_internal_add_entries() {
  return _impl_.entries_.Add();
}
inline ::gluten::shard::proto::ShardLookupEntry* BatchLookupRequest::add_entries() {
  ::gluten::shard::proto::ShardLookupEntry* _add = _internal_add_entries();
  // @@protoc_insertion_point(field_add:gluten.shard.proto.BatchLookupRequest.entries)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gluten::shard::proto::ShardLookupEntry >&
BatchLookupRequest::entries() const {
  // @@protoc_insertion_point(field_list:gluten.shard.proto.BatchLookupRequest.entries)
  return _impl_.entries_;
}

// -------------------------------------------------------------------

// BatchLookupResponse

// repeated .gluten.shard.proto.ShardLookupResultEntry results = 1;
inline int BatchLookupResponse::_internal_results_size() const {
  return _impl_.results_.size();
}
inline int BatchLookupResponse::results_size() const {
  return _internal_results_size();
}
inline void BatchLookupResponse::clear_results() {
  _impl_.results_.Clear();
}
inline ::gluten::shard::proto::ShardLookupResultEntry* BatchLookupResponse::mutable_results(int index) {
  // @@protoc_insertion_point(field_mutable:gluten.shard.proto.BatchLookupResponse.results)
  return _impl_.results_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gluten::shard::proto::ShardLookupResultEntry >*
BatchLookupResponse::mutable_results() {
  // @@protoc_insertion_point(field_mutable_list:gluten.shard.proto.BatchLookupResponse.results)
  return &_impl_.results_;
}
inline const ::gluten::shard::proto::ShardLookupResultEntry& BatchLookupResponse::_internal_results(int index) const {
  return _impl_.results_.Get(index);
}
inline const ::gluten::shard::proto::ShardLookupResultEntry& BatchLookupResponse::results(int index) const {
  // @@protoc_insertion_point(field_get:gluten.shard.proto.BatchLookupResponse.results)
  return _internal_results(index);
}
inline ::gluten::shard::proto::ShardLookupResultEntry* BatchLookupResponse::_internal_add_results() {
  return _impl_.results_.Add();
}
inline ::gluten::shard::proto::ShardLookupResultEntry* BatchLookupResponse::add_results() {
  ::gluten::shard::proto::ShardLookupResultEntry* _add = _internal_add_results();
  // @@protoc_insertion_point(field_add:gluten.shard.proto.BatchLookupResponse.results)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gluten::shard::proto::ShardLookupResultEntry >&
BatchLookupResponse::results() const {
  // @@protoc_insertion_point(field_list:gluten.shard.proto.BatchLookupResponse.results)
  return _impl_.results_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace shard
}  // namespace gluten

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_shard_5flookup_2eproto
