// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shard_lookup.proto

#include "shard_lookup.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace gluten {
namespace shard {
namespace proto {
PROTOBUF_CONSTEXPR LookupRequest::LookupRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.input_indices_)*/{}
  , /*decltype(_impl_._input_indices_cached_byte_size_)*/{0}
  , /*decltype(_impl_.probe_keys_compact_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.probe_filter_columns_compact_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.filter_expression_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.probe_columns_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.filter_input_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.set_id_)*/int64_t{0}
  , /*decltype(_impl_.shard_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LookupRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LookupRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LookupRequestDefaultTypeInternal() {}
  union {
    LookupRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LookupRequestDefaultTypeInternal _LookupRequest_default_instance_;
PROTOBUF_CONSTEXPR LookupResponse::LookupResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.input_hits_)*/{}
  , /*decltype(_impl_._input_hits_cached_byte_size_)*/{0}
  , /*decltype(_impl_.output_compact_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LookupResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LookupResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LookupResponseDefaultTypeInternal() {}
  union {
    LookupResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LookupResponseDefaultTypeInternal _LookupResponse_default_instance_;
PROTOBUF_CONSTEXPR ShardLookupEntry::ShardLookupEntry(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.input_indices_)*/{}
  , /*decltype(_impl_._input_indices_cached_byte_size_)*/{0}
  , /*decltype(_impl_.probe_keys_compact_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.probe_filter_columns_compact_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.filter_expression_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.probe_columns_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.filter_input_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.shard_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ShardLookupEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ShardLookupEntryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ShardLookupEntryDefaultTypeInternal() {}
  union {
    ShardLookupEntry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShardLookupEntryDefaultTypeInternal _ShardLookupEntry_default_instance_;
PROTOBUF_CONSTEXPR ShardLookupResultEntry::ShardLookupResultEntry(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.input_hits_)*/{}
  , /*decltype(_impl_._input_hits_cached_byte_size_)*/{0}
  , /*decltype(_impl_.output_compact_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.shard_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ShardLookupResultEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ShardLookupResultEntryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ShardLookupResultEntryDefaultTypeInternal() {}
  union {
    ShardLookupResultEntry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShardLookupResultEntryDefaultTypeInternal _ShardLookupResultEntry_default_instance_;
PROTOBUF_CONSTEXPR BatchLookupRequest::BatchLookupRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entries_)*/{}
  , /*decltype(_impl_.set_id_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BatchLookupRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BatchLookupRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BatchLookupRequestDefaultTypeInternal() {}
  union {
    BatchLookupRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BatchLookupRequestDefaultTypeInternal _BatchLookupRequest_default_instance_;
PROTOBUF_CONSTEXPR BatchLookupResponse::BatchLookupResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.results_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BatchLookupResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BatchLookupResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BatchLookupResponseDefaultTypeInternal() {}
  union {
    BatchLookupResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BatchLookupResponseDefaultTypeInternal _BatchLookupResponse_default_instance_;
}  // namespace proto
}  // namespace shard
}  // namespace gluten
static ::_pb::Metadata file_level_metadata_shard_5flookup_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_shard_5flookup_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_shard_5flookup_2eproto = nullptr;

const uint32_t TableStruct_shard_5flookup_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupRequest, _impl_.set_id_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupRequest, _impl_.shard_id_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupRequest, _impl_.probe_keys_compact_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupRequest, _impl_.input_indices_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupRequest, _impl_.probe_filter_columns_compact_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupRequest, _impl_.filter_expression_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupRequest, _impl_.probe_columns_type_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupRequest, _impl_.filter_input_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupResponse, _impl_.output_compact_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::LookupResponse, _impl_.input_hits_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupEntry, _impl_.shard_id_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupEntry, _impl_.probe_keys_compact_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupEntry, _impl_.input_indices_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupEntry, _impl_.probe_filter_columns_compact_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupEntry, _impl_.filter_expression_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupEntry, _impl_.probe_columns_type_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupEntry, _impl_.filter_input_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupResultEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupResultEntry, _impl_.shard_id_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupResultEntry, _impl_.output_compact_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::ShardLookupResultEntry, _impl_.input_hits_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::BatchLookupRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::BatchLookupRequest, _impl_.set_id_),
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::BatchLookupRequest, _impl_.entries_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::BatchLookupResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::gluten::shard::proto::BatchLookupResponse, _impl_.results_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::gluten::shard::proto::LookupRequest)},
  { 14, -1, -1, sizeof(::gluten::shard::proto::LookupResponse)},
  { 22, -1, -1, sizeof(::gluten::shard::proto::ShardLookupEntry)},
  { 35, -1, -1, sizeof(::gluten::shard::proto::ShardLookupResultEntry)},
  { 44, -1, -1, sizeof(::gluten::shard::proto::BatchLookupRequest)},
  { 52, -1, -1, sizeof(::gluten::shard::proto::BatchLookupResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::gluten::shard::proto::_LookupRequest_default_instance_._instance,
  &::gluten::shard::proto::_LookupResponse_default_instance_._instance,
  &::gluten::shard::proto::_ShardLookupEntry_default_instance_._instance,
  &::gluten::shard::proto::_ShardLookupResultEntry_default_instance_._instance,
  &::gluten::shard::proto::_BatchLookupRequest_default_instance_._instance,
  &::gluten::shard::proto::_BatchLookupResponse_default_instance_._instance,
};

const char descriptor_table_protodef_shard_5flookup_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022shard_lookup.proto\022\022gluten.shard.proto"
  "\"\334\001\n\rLookupRequest\022\016\n\006set_id\030\001 \001(\003\022\020\n\010sh"
  "ard_id\030\002 \001(\005\022\032\n\022probe_keys_compact\030\003 \001(\014"
  "\022\025\n\rinput_indices\030\004 \003(\005\022$\n\034probe_filter_"
  "columns_compact\030\005 \001(\014\022\031\n\021filter_expressi"
  "on\030\006 \001(\t\022\032\n\022probe_columns_type\030\007 \001(\t\022\031\n\021"
  "filter_input_type\030\010 \001(\t\"<\n\016LookupRespons"
  "e\022\026\n\016output_compact\030\001 \001(\014\022\022\n\ninput_hits\030"
  "\002 \003(\005\"\317\001\n\020ShardLookupEntry\022\020\n\010shard_id\030\001"
  " \001(\005\022\032\n\022probe_keys_compact\030\002 \001(\014\022\025\n\rinpu"
  "t_indices\030\003 \003(\005\022$\n\034probe_filter_columns_"
  "compact\030\004 \001(\014\022\031\n\021filter_expression\030\005 \001(\t"
  "\022\032\n\022probe_columns_type\030\006 \001(\t\022\031\n\021filter_i"
  "nput_type\030\007 \001(\t\"V\n\026ShardLookupResultEntr"
  "y\022\020\n\010shard_id\030\001 \001(\005\022\026\n\016output_compact\030\002 "
  "\001(\014\022\022\n\ninput_hits\030\003 \003(\005\"[\n\022BatchLookupRe"
  "quest\022\016\n\006set_id\030\001 \001(\003\0225\n\007entries\030\002 \003(\0132$"
  ".gluten.shard.proto.ShardLookupEntry\"R\n\023"
  "BatchLookupResponse\022;\n\007results\030\001 \003(\0132*.g"
  "luten.shard.proto.ShardLookupResultEntry"
  "2\305\001\n\022ShardLookupService\022O\n\006Lookup\022!.glut"
  "en.shard.proto.LookupRequest\032\".gluten.sh"
  "ard.proto.LookupResponse\022^\n\013BatchLookup\022"
  "&.gluten.shard.proto.BatchLookupRequest\032"
  "\'.gluten.shard.proto.BatchLookupResponse"
  "B1\n\035org.apache.gluten.shard.protoB\020Shard"
  "LookupProtob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_shard_5flookup_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_shard_5flookup_2eproto = {
    false, false, 1059, descriptor_table_protodef_shard_5flookup_2eproto,
    "shard_lookup.proto",
    &descriptor_table_shard_5flookup_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_shard_5flookup_2eproto::offsets,
    file_level_metadata_shard_5flookup_2eproto, file_level_enum_descriptors_shard_5flookup_2eproto,
    file_level_service_descriptors_shard_5flookup_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_shard_5flookup_2eproto_getter() {
  return &descriptor_table_shard_5flookup_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_shard_5flookup_2eproto(&descriptor_table_shard_5flookup_2eproto);
namespace gluten {
namespace shard {
namespace proto {

// ===================================================================

class LookupRequest::_Internal {
 public:
};

LookupRequest::LookupRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gluten.shard.proto.LookupRequest)
}
LookupRequest::LookupRequest(const LookupRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LookupRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.input_indices_){from._impl_.input_indices_}
    , /*decltype(_impl_._input_indices_cached_byte_size_)*/{0}
    , decltype(_impl_.probe_keys_compact_){}
    , decltype(_impl_.probe_filter_columns_compact_){}
    , decltype(_impl_.filter_expression_){}
    , decltype(_impl_.probe_columns_type_){}
    , decltype(_impl_.filter_input_type_){}
    , decltype(_impl_.set_id_){}
    , decltype(_impl_.shard_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.probe_keys_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_keys_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_probe_keys_compact().empty()) {
    _this->_impl_.probe_keys_compact_.Set(from._internal_probe_keys_compact(), 
      _this->GetArenaForAllocation());
  }
  _impl_.probe_filter_columns_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_filter_columns_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_probe_filter_columns_compact().empty()) {
    _this->_impl_.probe_filter_columns_compact_.Set(from._internal_probe_filter_columns_compact(), 
      _this->GetArenaForAllocation());
  }
  _impl_.filter_expression_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filter_expression_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filter_expression().empty()) {
    _this->_impl_.filter_expression_.Set(from._internal_filter_expression(), 
      _this->GetArenaForAllocation());
  }
  _impl_.probe_columns_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_columns_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_probe_columns_type().empty()) {
    _this->_impl_.probe_columns_type_.Set(from._internal_probe_columns_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.filter_input_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filter_input_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filter_input_type().empty()) {
    _this->_impl_.filter_input_type_.Set(from._internal_filter_input_type(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.set_id_, &from._impl_.set_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.shard_id_) -
    reinterpret_cast<char*>(&_impl_.set_id_)) + sizeof(_impl_.shard_id_));
  // @@protoc_insertion_point(copy_constructor:gluten.shard.proto.LookupRequest)
}

inline void LookupRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.input_indices_){arena}
    , /*decltype(_impl_._input_indices_cached_byte_size_)*/{0}
    , decltype(_impl_.probe_keys_compact_){}
    , decltype(_impl_.probe_filter_columns_compact_){}
    , decltype(_impl_.filter_expression_){}
    , decltype(_impl_.probe_columns_type_){}
    , decltype(_impl_.filter_input_type_){}
    , decltype(_impl_.set_id_){int64_t{0}}
    , decltype(_impl_.shard_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.probe_keys_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_keys_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.probe_filter_columns_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_filter_columns_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.filter_expression_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filter_expression_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.probe_columns_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_columns_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.filter_input_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filter_input_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LookupRequest::~LookupRequest() {
  // @@protoc_insertion_point(destructor:gluten.shard.proto.LookupRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LookupRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.input_indices_.~RepeatedField();
  _impl_.probe_keys_compact_.Destroy();
  _impl_.probe_filter_columns_compact_.Destroy();
  _impl_.filter_expression_.Destroy();
  _impl_.probe_columns_type_.Destroy();
  _impl_.filter_input_type_.Destroy();
}

void LookupRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LookupRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:gluten.shard.proto.LookupRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.input_indices_.Clear();
  _impl_.probe_keys_compact_.ClearToEmpty();
  _impl_.probe_filter_columns_compact_.ClearToEmpty();
  _impl_.filter_expression_.ClearToEmpty();
  _impl_.probe_columns_type_.ClearToEmpty();
  _impl_.filter_input_type_.ClearToEmpty();
  ::memset(&_impl_.set_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.shard_id_) -
      reinterpret_cast<char*>(&_impl_.set_id_)) + sizeof(_impl_.shard_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LookupRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 set_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.set_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 shard_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.shard_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes probe_keys_compact = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_probe_keys_compact();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 input_indices = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_input_indices(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 32) {
          _internal_add_input_indices(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes probe_filter_columns_compact = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_probe_filter_columns_compact();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string filter_expression = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_filter_expression();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "gluten.shard.proto.LookupRequest.filter_expression"));
        } else
          goto handle_unusual;
        continue;
      // string probe_columns_type = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_probe_columns_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "gluten.shard.proto.LookupRequest.probe_columns_type"));
        } else
          goto handle_unusual;
        continue;
      // string filter_input_type = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_filter_input_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "gluten.shard.proto.LookupRequest.filter_input_type"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LookupRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gluten.shard.proto.LookupRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 set_id = 1;
  if (this->_internal_set_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_set_id(), target);
  }

  // int32 shard_id = 2;
  if (this->_internal_shard_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_shard_id(), target);
  }

  // bytes probe_keys_compact = 3;
  if (!this->_internal_probe_keys_compact().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_probe_keys_compact(), target);
  }

  // repeated int32 input_indices = 4;
  {
    int byte_size = _impl_._input_indices_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          4, _internal_input_indices(), byte_size, target);
    }
  }

  // bytes probe_filter_columns_compact = 5;
  if (!this->_internal_probe_filter_columns_compact().empty()) {
    target = stream->WriteBytesMaybeAliased(
        5, this->_internal_probe_filter_columns_compact(), target);
  }

  // string filter_expression = 6;
  if (!this->_internal_filter_expression().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filter_expression().data(), static_cast<int>(this->_internal_filter_expression().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gluten.shard.proto.LookupRequest.filter_expression");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_filter_expression(), target);
  }

  // string probe_columns_type = 7;
  if (!this->_internal_probe_columns_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_probe_columns_type().data(), static_cast<int>(this->_internal_probe_columns_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gluten.shard.proto.LookupRequest.probe_columns_type");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_probe_columns_type(), target);
  }

  // string filter_input_type = 8;
  if (!this->_internal_filter_input_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filter_input_type().data(), static_cast<int>(this->_internal_filter_input_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gluten.shard.proto.LookupRequest.filter_input_type");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_filter_input_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gluten.shard.proto.LookupRequest)
  return target;
}

size_t LookupRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gluten.shard.proto.LookupRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 input_indices = 4;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.input_indices_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._input_indices_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // bytes probe_keys_compact = 3;
  if (!this->_internal_probe_keys_compact().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_probe_keys_compact());
  }

  // bytes probe_filter_columns_compact = 5;
  if (!this->_internal_probe_filter_columns_compact().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_probe_filter_columns_compact());
  }

  // string filter_expression = 6;
  if (!this->_internal_filter_expression().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filter_expression());
  }

  // string probe_columns_type = 7;
  if (!this->_internal_probe_columns_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_probe_columns_type());
  }

  // string filter_input_type = 8;
  if (!this->_internal_filter_input_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filter_input_type());
  }

  // int64 set_id = 1;
  if (this->_internal_set_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_set_id());
  }

  // int32 shard_id = 2;
  if (this->_internal_shard_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_shard_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LookupRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LookupRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LookupRequest::GetClassData() const { return &_class_data_; }


void LookupRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LookupRequest*>(&to_msg);
  auto& from = static_cast<const LookupRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gluten.shard.proto.LookupRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.input_indices_.MergeFrom(from._impl_.input_indices_);
  if (!from._internal_probe_keys_compact().empty()) {
    _this->_internal_set_probe_keys_compact(from._internal_probe_keys_compact());
  }
  if (!from._internal_probe_filter_columns_compact().empty()) {
    _this->_internal_set_probe_filter_columns_compact(from._internal_probe_filter_columns_compact());
  }
  if (!from._internal_filter_expression().empty()) {
    _this->_internal_set_filter_expression(from._internal_filter_expression());
  }
  if (!from._internal_probe_columns_type().empty()) {
    _this->_internal_set_probe_columns_type(from._internal_probe_columns_type());
  }
  if (!from._internal_filter_input_type().empty()) {
    _this->_internal_set_filter_input_type(from._internal_filter_input_type());
  }
  if (from._internal_set_id() != 0) {
    _this->_internal_set_set_id(from._internal_set_id());
  }
  if (from._internal_shard_id() != 0) {
    _this->_internal_set_shard_id(from._internal_shard_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LookupRequest::CopyFrom(const LookupRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gluten.shard.proto.LookupRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LookupRequest::IsInitialized() const {
  return true;
}

void LookupRequest::InternalSwap(LookupRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.input_indices_.InternalSwap(&other->_impl_.input_indices_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.probe_keys_compact_, lhs_arena,
      &other->_impl_.probe_keys_compact_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.probe_filter_columns_compact_, lhs_arena,
      &other->_impl_.probe_filter_columns_compact_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filter_expression_, lhs_arena,
      &other->_impl_.filter_expression_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.probe_columns_type_, lhs_arena,
      &other->_impl_.probe_columns_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filter_input_type_, lhs_arena,
      &other->_impl_.filter_input_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LookupRequest, _impl_.shard_id_)
      + sizeof(LookupRequest::_impl_.shard_id_)
      - PROTOBUF_FIELD_OFFSET(LookupRequest, _impl_.set_id_)>(
          reinterpret_cast<char*>(&_impl_.set_id_),
          reinterpret_cast<char*>(&other->_impl_.set_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LookupRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_shard_5flookup_2eproto_getter, &descriptor_table_shard_5flookup_2eproto_once,
      file_level_metadata_shard_5flookup_2eproto[0]);
}

// ===================================================================

class LookupResponse::_Internal {
 public:
};

LookupResponse::LookupResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gluten.shard.proto.LookupResponse)
}
LookupResponse::LookupResponse(const LookupResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LookupResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.input_hits_){from._impl_.input_hits_}
    , /*decltype(_impl_._input_hits_cached_byte_size_)*/{0}
    , decltype(_impl_.output_compact_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.output_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.output_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_output_compact().empty()) {
    _this->_impl_.output_compact_.Set(from._internal_output_compact(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:gluten.shard.proto.LookupResponse)
}

inline void LookupResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.input_hits_){arena}
    , /*decltype(_impl_._input_hits_cached_byte_size_)*/{0}
    , decltype(_impl_.output_compact_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.output_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.output_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LookupResponse::~LookupResponse() {
  // @@protoc_insertion_point(destructor:gluten.shard.proto.LookupResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LookupResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.input_hits_.~RepeatedField();
  _impl_.output_compact_.Destroy();
}

void LookupResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LookupResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:gluten.shard.proto.LookupResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.input_hits_.Clear();
  _impl_.output_compact_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LookupResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes output_compact = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_output_compact();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 input_hits = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_input_hits(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_input_hits(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LookupResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gluten.shard.proto.LookupResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes output_compact = 1;
  if (!this->_internal_output_compact().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_output_compact(), target);
  }

  // repeated int32 input_hits = 2;
  {
    int byte_size = _impl_._input_hits_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          2, _internal_input_hits(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gluten.shard.proto.LookupResponse)
  return target;
}

size_t LookupResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gluten.shard.proto.LookupResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 input_hits = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.input_hits_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._input_hits_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // bytes output_compact = 1;
  if (!this->_internal_output_compact().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_output_compact());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LookupResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LookupResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LookupResponse::GetClassData() const { return &_class_data_; }


void LookupResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LookupResponse*>(&to_msg);
  auto& from = static_cast<const LookupResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gluten.shard.proto.LookupResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.input_hits_.MergeFrom(from._impl_.input_hits_);
  if (!from._internal_output_compact().empty()) {
    _this->_internal_set_output_compact(from._internal_output_compact());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LookupResponse::CopyFrom(const LookupResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gluten.shard.proto.LookupResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LookupResponse::IsInitialized() const {
  return true;
}

void LookupResponse::InternalSwap(LookupResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.input_hits_.InternalSwap(&other->_impl_.input_hits_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.output_compact_, lhs_arena,
      &other->_impl_.output_compact_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata LookupResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_shard_5flookup_2eproto_getter, &descriptor_table_shard_5flookup_2eproto_once,
      file_level_metadata_shard_5flookup_2eproto[1]);
}

// ===================================================================

class ShardLookupEntry::_Internal {
 public:
};

ShardLookupEntry::ShardLookupEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gluten.shard.proto.ShardLookupEntry)
}
ShardLookupEntry::ShardLookupEntry(const ShardLookupEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ShardLookupEntry* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.input_indices_){from._impl_.input_indices_}
    , /*decltype(_impl_._input_indices_cached_byte_size_)*/{0}
    , decltype(_impl_.probe_keys_compact_){}
    , decltype(_impl_.probe_filter_columns_compact_){}
    , decltype(_impl_.filter_expression_){}
    , decltype(_impl_.probe_columns_type_){}
    , decltype(_impl_.filter_input_type_){}
    , decltype(_impl_.shard_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.probe_keys_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_keys_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_probe_keys_compact().empty()) {
    _this->_impl_.probe_keys_compact_.Set(from._internal_probe_keys_compact(), 
      _this->GetArenaForAllocation());
  }
  _impl_.probe_filter_columns_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_filter_columns_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_probe_filter_columns_compact().empty()) {
    _this->_impl_.probe_filter_columns_compact_.Set(from._internal_probe_filter_columns_compact(), 
      _this->GetArenaForAllocation());
  }
  _impl_.filter_expression_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filter_expression_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filter_expression().empty()) {
    _this->_impl_.filter_expression_.Set(from._internal_filter_expression(), 
      _this->GetArenaForAllocation());
  }
  _impl_.probe_columns_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_columns_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_probe_columns_type().empty()) {
    _this->_impl_.probe_columns_type_.Set(from._internal_probe_columns_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.filter_input_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filter_input_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_filter_input_type().empty()) {
    _this->_impl_.filter_input_type_.Set(from._internal_filter_input_type(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.shard_id_ = from._impl_.shard_id_;
  // @@protoc_insertion_point(copy_constructor:gluten.shard.proto.ShardLookupEntry)
}

inline void ShardLookupEntry::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.input_indices_){arena}
    , /*decltype(_impl_._input_indices_cached_byte_size_)*/{0}
    , decltype(_impl_.probe_keys_compact_){}
    , decltype(_impl_.probe_filter_columns_compact_){}
    , decltype(_impl_.filter_expression_){}
    , decltype(_impl_.probe_columns_type_){}
    , decltype(_impl_.filter_input_type_){}
    , decltype(_impl_.shard_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.probe_keys_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_keys_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.probe_filter_columns_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_filter_columns_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.filter_expression_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filter_expression_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.probe_columns_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.probe_columns_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.filter_input_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.filter_input_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ShardLookupEntry::~ShardLookupEntry() {
  // @@protoc_insertion_point(destructor:gluten.shard.proto.ShardLookupEntry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ShardLookupEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.input_indices_.~RepeatedField();
  _impl_.probe_keys_compact_.Destroy();
  _impl_.probe_filter_columns_compact_.Destroy();
  _impl_.filter_expression_.Destroy();
  _impl_.probe_columns_type_.Destroy();
  _impl_.filter_input_type_.Destroy();
}

void ShardLookupEntry::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ShardLookupEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:gluten.shard.proto.ShardLookupEntry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.input_indices_.Clear();
  _impl_.probe_keys_compact_.ClearToEmpty();
  _impl_.probe_filter_columns_compact_.ClearToEmpty();
  _impl_.filter_expression_.ClearToEmpty();
  _impl_.probe_columns_type_.ClearToEmpty();
  _impl_.filter_input_type_.ClearToEmpty();
  _impl_.shard_id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ShardLookupEntry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 shard_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.shard_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes probe_keys_compact = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_probe_keys_compact();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 input_indices = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_input_indices(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 24) {
          _internal_add_input_indices(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes probe_filter_columns_compact = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_probe_filter_columns_compact();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string filter_expression = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_filter_expression();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "gluten.shard.proto.ShardLookupEntry.filter_expression"));
        } else
          goto handle_unusual;
        continue;
      // string probe_columns_type = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_probe_columns_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "gluten.shard.proto.ShardLookupEntry.probe_columns_type"));
        } else
          goto handle_unusual;
        continue;
      // string filter_input_type = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_filter_input_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "gluten.shard.proto.ShardLookupEntry.filter_input_type"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ShardLookupEntry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gluten.shard.proto.ShardLookupEntry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 shard_id = 1;
  if (this->_internal_shard_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_shard_id(), target);
  }

  // bytes probe_keys_compact = 2;
  if (!this->_internal_probe_keys_compact().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_probe_keys_compact(), target);
  }

  // repeated int32 input_indices = 3;
  {
    int byte_size = _impl_._input_indices_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          3, _internal_input_indices(), byte_size, target);
    }
  }

  // bytes probe_filter_columns_compact = 4;
  if (!this->_internal_probe_filter_columns_compact().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_probe_filter_columns_compact(), target);
  }

  // string filter_expression = 5;
  if (!this->_internal_filter_expression().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filter_expression().data(), static_cast<int>(this->_internal_filter_expression().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gluten.shard.proto.ShardLookupEntry.filter_expression");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_filter_expression(), target);
  }

  // string probe_columns_type = 6;
  if (!this->_internal_probe_columns_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_probe_columns_type().data(), static_cast<int>(this->_internal_probe_columns_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gluten.shard.proto.ShardLookupEntry.probe_columns_type");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_probe_columns_type(), target);
  }

  // string filter_input_type = 7;
  if (!this->_internal_filter_input_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_filter_input_type().data(), static_cast<int>(this->_internal_filter_input_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gluten.shard.proto.ShardLookupEntry.filter_input_type");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_filter_input_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gluten.shard.proto.ShardLookupEntry)
  return target;
}

size_t ShardLookupEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gluten.shard.proto.ShardLookupEntry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 input_indices = 3;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.input_indices_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._input_indices_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // bytes probe_keys_compact = 2;
  if (!this->_internal_probe_keys_compact().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_probe_keys_compact());
  }

  // bytes probe_filter_columns_compact = 4;
  if (!this->_internal_probe_filter_columns_compact().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_probe_filter_columns_compact());
  }

  // string filter_expression = 5;
  if (!this->_internal_filter_expression().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filter_expression());
  }

  // string probe_columns_type = 6;
  if (!this->_internal_probe_columns_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_probe_columns_type());
  }

  // string filter_input_type = 7;
  if (!this->_internal_filter_input_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_filter_input_type());
  }

  // int32 shard_id = 1;
  if (this->_internal_shard_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_shard_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ShardLookupEntry::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ShardLookupEntry::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ShardLookupEntry::GetClassData() const { return &_class_data_; }


void ShardLookupEntry::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ShardLookupEntry*>(&to_msg);
  auto& from = static_cast<const ShardLookupEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gluten.shard.proto.ShardLookupEntry)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.input_indices_.MergeFrom(from._impl_.input_indices_);
  if (!from._internal_probe_keys_compact().empty()) {
    _this->_internal_set_probe_keys_compact(from._internal_probe_keys_compact());
  }
  if (!from._internal_probe_filter_columns_compact().empty()) {
    _this->_internal_set_probe_filter_columns_compact(from._internal_probe_filter_columns_compact());
  }
  if (!from._internal_filter_expression().empty()) {
    _this->_internal_set_filter_expression(from._internal_filter_expression());
  }
  if (!from._internal_probe_columns_type().empty()) {
    _this->_internal_set_probe_columns_type(from._internal_probe_columns_type());
  }
  if (!from._internal_filter_input_type().empty()) {
    _this->_internal_set_filter_input_type(from._internal_filter_input_type());
  }
  if (from._internal_shard_id() != 0) {
    _this->_internal_set_shard_id(from._internal_shard_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ShardLookupEntry::CopyFrom(const ShardLookupEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gluten.shard.proto.ShardLookupEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShardLookupEntry::IsInitialized() const {
  return true;
}

void ShardLookupEntry::InternalSwap(ShardLookupEntry* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.input_indices_.InternalSwap(&other->_impl_.input_indices_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.probe_keys_compact_, lhs_arena,
      &other->_impl_.probe_keys_compact_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.probe_filter_columns_compact_, lhs_arena,
      &other->_impl_.probe_filter_columns_compact_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filter_expression_, lhs_arena,
      &other->_impl_.filter_expression_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.probe_columns_type_, lhs_arena,
      &other->_impl_.probe_columns_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.filter_input_type_, lhs_arena,
      &other->_impl_.filter_input_type_, rhs_arena
  );
  swap(_impl_.shard_id_, other->_impl_.shard_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ShardLookupEntry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_shard_5flookup_2eproto_getter, &descriptor_table_shard_5flookup_2eproto_once,
      file_level_metadata_shard_5flookup_2eproto[2]);
}

// ===================================================================

class ShardLookupResultEntry::_Internal {
 public:
};

ShardLookupResultEntry::ShardLookupResultEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gluten.shard.proto.ShardLookupResultEntry)
}
ShardLookupResultEntry::ShardLookupResultEntry(const ShardLookupResultEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ShardLookupResultEntry* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.input_hits_){from._impl_.input_hits_}
    , /*decltype(_impl_._input_hits_cached_byte_size_)*/{0}
    , decltype(_impl_.output_compact_){}
    , decltype(_impl_.shard_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.output_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.output_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_output_compact().empty()) {
    _this->_impl_.output_compact_.Set(from._internal_output_compact(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.shard_id_ = from._impl_.shard_id_;
  // @@protoc_insertion_point(copy_constructor:gluten.shard.proto.ShardLookupResultEntry)
}

inline void ShardLookupResultEntry::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.input_hits_){arena}
    , /*decltype(_impl_._input_hits_cached_byte_size_)*/{0}
    , decltype(_impl_.output_compact_){}
    , decltype(_impl_.shard_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.output_compact_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.output_compact_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ShardLookupResultEntry::~ShardLookupResultEntry() {
  // @@protoc_insertion_point(destructor:gluten.shard.proto.ShardLookupResultEntry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ShardLookupResultEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.input_hits_.~RepeatedField();
  _impl_.output_compact_.Destroy();
}

void ShardLookupResultEntry::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ShardLookupResultEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:gluten.shard.proto.ShardLookupResultEntry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.input_hits_.Clear();
  _impl_.output_compact_.ClearToEmpty();
  _impl_.shard_id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ShardLookupResultEntry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 shard_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.shard_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes output_compact = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_output_compact();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 input_hits = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_input_hits(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 24) {
          _internal_add_input_hits(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ShardLookupResultEntry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gluten.shard.proto.ShardLookupResultEntry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 shard_id = 1;
  if (this->_internal_shard_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_shard_id(), target);
  }

  // bytes output_compact = 2;
  if (!this->_internal_output_compact().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_output_compact(), target);
  }

  // repeated int32 input_hits = 3;
  {
    int byte_size = _impl_._input_hits_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          3, _internal_input_hits(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gluten.shard.proto.ShardLookupResultEntry)
  return target;
}

size_t ShardLookupResultEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gluten.shard.proto.ShardLookupResultEntry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 input_hits = 3;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.input_hits_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._input_hits_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // bytes output_compact = 2;
  if (!this->_internal_output_compact().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_output_compact());
  }

  // int32 shard_id = 1;
  if (this->_internal_shard_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_shard_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ShardLookupResultEntry::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ShardLookupResultEntry::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ShardLookupResultEntry::GetClassData() const { return &_class_data_; }


void ShardLookupResultEntry::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ShardLookupResultEntry*>(&to_msg);
  auto& from = static_cast<const ShardLookupResultEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gluten.shard.proto.ShardLookupResultEntry)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.input_hits_.MergeFrom(from._impl_.input_hits_);
  if (!from._internal_output_compact().empty()) {
    _this->_internal_set_output_compact(from._internal_output_compact());
  }
  if (from._internal_shard_id() != 0) {
    _this->_internal_set_shard_id(from._internal_shard_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ShardLookupResultEntry::CopyFrom(const ShardLookupResultEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gluten.shard.proto.ShardLookupResultEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShardLookupResultEntry::IsInitialized() const {
  return true;
}

void ShardLookupResultEntry::InternalSwap(ShardLookupResultEntry* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.input_hits_.InternalSwap(&other->_impl_.input_hits_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.output_compact_, lhs_arena,
      &other->_impl_.output_compact_, rhs_arena
  );
  swap(_impl_.shard_id_, other->_impl_.shard_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ShardLookupResultEntry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_shard_5flookup_2eproto_getter, &descriptor_table_shard_5flookup_2eproto_once,
      file_level_metadata_shard_5flookup_2eproto[3]);
}

// ===================================================================

class BatchLookupRequest::_Internal {
 public:
};

BatchLookupRequest::BatchLookupRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gluten.shard.proto.BatchLookupRequest)
}
BatchLookupRequest::BatchLookupRequest(const BatchLookupRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BatchLookupRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entries_){from._impl_.entries_}
    , decltype(_impl_.set_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.set_id_ = from._impl_.set_id_;
  // @@protoc_insertion_point(copy_constructor:gluten.shard.proto.BatchLookupRequest)
}

inline void BatchLookupRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entries_){arena}
    , decltype(_impl_.set_id_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BatchLookupRequest::~BatchLookupRequest() {
  // @@protoc_insertion_point(destructor:gluten.shard.proto.BatchLookupRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BatchLookupRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.entries_.~RepeatedPtrField();
}

void BatchLookupRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BatchLookupRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:gluten.shard.proto.BatchLookupRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entries_.Clear();
  _impl_.set_id_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BatchLookupRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 set_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.set_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .gluten.shard.proto.ShardLookupEntry entries = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_entries(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BatchLookupRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gluten.shard.proto.BatchLookupRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 set_id = 1;
  if (this->_internal_set_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_set_id(), target);
  }

  // repeated .gluten.shard.proto.ShardLookupEntry entries = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_entries_size()); i < n; i++) {
    const auto& repfield = this->_internal_entries(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gluten.shard.proto.BatchLookupRequest)
  return target;
}

size_t BatchLookupRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gluten.shard.proto.BatchLookupRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .gluten.shard.proto.ShardLookupEntry entries = 2;
  total_size += 1UL * this->_internal_entries_size();
  for (const auto& msg : this->_impl_.entries_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int64 set_id = 1;
  if (this->_internal_set_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_set_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BatchLookupRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BatchLookupRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BatchLookupRequest::GetClassData() const { return &_class_data_; }


void BatchLookupRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BatchLookupRequest*>(&to_msg);
  auto& from = static_cast<const BatchLookupRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gluten.shard.proto.BatchLookupRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.entries_.MergeFrom(from._impl_.entries_);
  if (from._internal_set_id() != 0) {
    _this->_internal_set_set_id(from._internal_set_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BatchLookupRequest::CopyFrom(const BatchLookupRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gluten.shard.proto.BatchLookupRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BatchLookupRequest::IsInitialized() const {
  return true;
}

void BatchLookupRequest::InternalSwap(BatchLookupRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.entries_.InternalSwap(&other->_impl_.entries_);
  swap(_impl_.set_id_, other->_impl_.set_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BatchLookupRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_shard_5flookup_2eproto_getter, &descriptor_table_shard_5flookup_2eproto_once,
      file_level_metadata_shard_5flookup_2eproto[4]);
}

// ===================================================================

class BatchLookupResponse::_Internal {
 public:
};

BatchLookupResponse::BatchLookupResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:gluten.shard.proto.BatchLookupResponse)
}
BatchLookupResponse::BatchLookupResponse(const BatchLookupResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BatchLookupResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.results_){from._impl_.results_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:gluten.shard.proto.BatchLookupResponse)
}

inline void BatchLookupResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.results_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BatchLookupResponse::~BatchLookupResponse() {
  // @@protoc_insertion_point(destructor:gluten.shard.proto.BatchLookupResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BatchLookupResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.results_.~RepeatedPtrField();
}

void BatchLookupResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BatchLookupResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:gluten.shard.proto.BatchLookupResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.results_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BatchLookupResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .gluten.shard.proto.ShardLookupResultEntry results = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_results(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BatchLookupResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gluten.shard.proto.BatchLookupResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .gluten.shard.proto.ShardLookupResultEntry results = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_results_size()); i < n; i++) {
    const auto& repfield = this->_internal_results(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gluten.shard.proto.BatchLookupResponse)
  return target;
}

size_t BatchLookupResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gluten.shard.proto.BatchLookupResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .gluten.shard.proto.ShardLookupResultEntry results = 1;
  total_size += 1UL * this->_internal_results_size();
  for (const auto& msg : this->_impl_.results_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BatchLookupResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BatchLookupResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BatchLookupResponse::GetClassData() const { return &_class_data_; }


void BatchLookupResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BatchLookupResponse*>(&to_msg);
  auto& from = static_cast<const BatchLookupResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gluten.shard.proto.BatchLookupResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.results_.MergeFrom(from._impl_.results_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BatchLookupResponse::CopyFrom(const BatchLookupResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gluten.shard.proto.BatchLookupResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BatchLookupResponse::IsInitialized() const {
  return true;
}

void BatchLookupResponse::InternalSwap(BatchLookupResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.results_.InternalSwap(&other->_impl_.results_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BatchLookupResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_shard_5flookup_2eproto_getter, &descriptor_table_shard_5flookup_2eproto_once,
      file_level_metadata_shard_5flookup_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace shard
}  // namespace gluten
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::gluten::shard::proto::LookupRequest*
Arena::CreateMaybeMessage< ::gluten::shard::proto::LookupRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gluten::shard::proto::LookupRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::gluten::shard::proto::LookupResponse*
Arena::CreateMaybeMessage< ::gluten::shard::proto::LookupResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gluten::shard::proto::LookupResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::gluten::shard::proto::ShardLookupEntry*
Arena::CreateMaybeMessage< ::gluten::shard::proto::ShardLookupEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gluten::shard::proto::ShardLookupEntry >(arena);
}
template<> PROTOBUF_NOINLINE ::gluten::shard::proto::ShardLookupResultEntry*
Arena::CreateMaybeMessage< ::gluten::shard::proto::ShardLookupResultEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gluten::shard::proto::ShardLookupResultEntry >(arena);
}
template<> PROTOBUF_NOINLINE ::gluten::shard::proto::BatchLookupRequest*
Arena::CreateMaybeMessage< ::gluten::shard::proto::BatchLookupRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gluten::shard::proto::BatchLookupRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::gluten::shard::proto::BatchLookupResponse*
Arena::CreateMaybeMessage< ::gluten::shard::proto::BatchLookupResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::gluten::shard::proto::BatchLookupResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
